Repository Amsterdam-Team/Aflami, pull requests merged in 2025-08, with the labels that each got.

#312 Fix navigation bar padding
  ui/src/main/java/com/amsterdam/ui/screens/continueWatching/ContinueWatchingScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/topRated/TopRatedScreen.kt
Labels: fix

#315 Make grid adaptive
  ui/src/main/java/com/amsterdam/ui/components/AdaptiveGrid.kt
  ui/src/main/java/com/amsterdam/ui/components/adaptiveGrid.kt
  ui/src/main/java/com/amsterdam/ui/screens/continueWatching/component/ContinueWatchingMediaItemsGrid.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/UpcomingMoviesSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/companyProductionSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/gallerySection.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/moreLikeSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/topRated/component/TopRatedMediaItemsGrid.kt
Labels: fix, enhancement

#314 Fix: pagination request issue
  ui/src/main/java/com/amsterdam/ui/screens/search/actorSearch/SearchByActorScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/countrySearch/components/MoviesVerticalGrid.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/SuccessMediaItemsSection.kt
Labels: fix

#318 fix: show AppBar even when network error occurs
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
Labels: fix

#319 Fix search if duplicate keyword
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
Labels: fix

#321 Resolve emoji problem in mode picker.
  ui/src/main/java/com/amsterdam/ui/screens/home/component/MoodPickerCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/model/CardMood.kt
Labels: fix

#323 Fix Search Placeholder Flicker
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/RecentSearchesSection.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
Labels: fix, refactor

#326 Fix Several Crashes in Offline Mode
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/MovieRemoteDetailsLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImpl.kt
Labels: fix, refactor

#330 Profile screen UI, add the initial state and navigate to login on click on login.
  ui/src/main/java/com/amsterdam/ui/screens/profile/ProfileScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/HistoryAndRatingSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/LoggedInContent.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/NotLoggedInContent.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/ProfileImageSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/ProfileInfoSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/SettingsSection.kt
  ui/src/main/res/drawable-hdpi/profile_background_image.png
  ui/src/main/res/drawable-mdpi/profile_background_image.png
  ui/src/main/res/drawable-xhdpi/profile_background_image.png
  ui/src/main/res/drawable-xxhdpi/profile_background_image.png
  ui/src/main/res/drawable-xxxhdpi/profile_background_image.png
  viewModel/src/main/java/com/amsterdam/viewmodel/profile/ProfileEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/profile/ProfileInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/profile/ProfileUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/profile/ProfileViewModel.kt
Labels: feature

#328 Refactor/remove cache for search screen
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/RecentSearchRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/search/RecentSearchesUseCase.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/CategoryDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/MovieDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createLocalTvShowCategoryDto.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/AflamiDatabase.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/MovieDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/RecentSearchDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/TvShowDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/CategoryLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/RecentSearchLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImpl.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/CategoryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/utils/createLocalTvShowCategoryDto.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/CategoryRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/serviceProvider/MovieServiceProvider.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/serviceProvider/TvShowsServiceProvider.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/serviceProvider/implementation/MovieServiceProviderImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/serviceProvider/implementation/TvShowsServiceProviderImpl.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImplTest.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/LocalCategoryDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/MovieLocalSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/RecentSearchLocalSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/TvShowLocalSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/LocalSearchDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/MovieCategoryCrossRefDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/SearchMovieCrossRefDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/SearchTvShowCrossRefDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/TvShowCategoryCrossRefDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/relation/MovieWithCategories.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieWithCategoriesLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowGenreLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowWithCategoryLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/MovieGenreIdsRemoteLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/TvShowGenreIdsRemoteLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/TvShowRemoteLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/RecentSearchRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/utils/RecentSearchHandler.kt
  repository/src/main/java/com/amsterdam/repository/utils/RecentSearchHandlerImpl.kt
  repository/src/test/java/com/amsterdam/repository/repository/CategoryRepositoryImplTest.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/actorSearch/SearchByActorScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
Labels: refactor

#332 refactor: rename variable for clarity and consistency
  app/src/main/java/com/amsterdam/aflami/di/apiServiceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
Labels: refactor

#325 Feature/add trailer video to movie and tvshow
  designSystem/src/main/java/com/amsterdam/designsystem/utils/IconManager.kt
  entity/src/main/java/com/amsterdam/entity/Episode.kt
  entity/src/main/java/com/amsterdam/entity/Movie.kt
  entity/src/main/java/com/amsterdam/entity/TvShow.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/MovieApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/TvShowsApiService.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/LocalMovieDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/EpisodeDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/RemoteMovieDetailsResponse.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/TvShowDetailsRemoteResponse.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/VideoDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/VideoResponse.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/EpisodeRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/MovieDetailRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/MovieRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/TvShowDetailsRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/MovieRemoteLocalMapper.kt
  ui/src/main/java/com/amsterdam/ui/application/MainActivity.kt
  ui/src/main/java/com/amsterdam/ui/screens/VideoLauncher.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/PlayButton.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsIntractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
Labels: feature

#334 Test/remote data source module test coverage
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/AuthenticationRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/CategoryRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/CountryRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImplTest.kt
Labels: Testing

#336 refactor: remove production companies from movie and TV show entities
  domain/src/main/java/com/amsterdam/domain/useCase/details/GetMovieDetailsUseCase.kt
  entity/src/main/java/com/amsterdam/entity/Movie.kt
  entity/src/main/java/com/amsterdam/entity/TvShow.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieWithCategoriesLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowWithCategoryLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/MovieDetailRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/MovieRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/TvShowDetailsRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/TvShowRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/MovieRemoteDetailsLocalMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiStateMapper.kt
Labels: refactor

#348 Update navigation to preserve backstack state on bottom navigation
  ui/src/main/java/com/amsterdam/ui/application/AflamiApp.kt
  ui/src/main/java/com/amsterdam/ui/screens/onBoarding/OnboardingScreen.kt
Labels: fix

#344 refactor: convert all mapper classes to extension functions
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImpl.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/LocalMovieDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/LocalTvShowDto.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/CountryLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieCategoryLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieGenreLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieWatchHistoryLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieWithCategoriesLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/RecentSearchLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/SessionTypeMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowCategoryLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowGenreLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowWithCategoryLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvWatchHistoryLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/CastRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/CategoryRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/CountryRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/EpisodeRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/GalleryRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/MovieDetailRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/MovieRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/PostersRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/ProductionCompanyRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/ReviewRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/SeasonRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/TvShowDetailsRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/TvShowRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/CountryRemoteLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/MovieCategoryRemoteLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/MovieRemoteDetailsLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/MovieRemoteLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/TvShowCategoryRemoteLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/TvShowRemoteDetailsLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remoteToLocal/TvShowRemoteLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/shared/DtoMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/shared/EntityMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/shared/GenreMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/shared/RemoteToLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/AuthenticationRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/CategoryRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/CountryRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/RecentSearchRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImpl.kt
Labels: refactor

#340 Increase domain module test coverage and add new test cases
  domain/src/test/java/com/amsterdam/domain/useCase/RecentSearchesUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/authentication/GetsSessionTypeTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/authentication/LoginAsGuestUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/preferences/GetOnboardingStatusUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/preferences/ManageLocaleLanguageUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/preferences/SetOnboardingCompletedUseCaseTest.kt
Labels: Testing

#338 Feature/list details
  app/src/main/java/com/amsterdam/aflami/di/apiServiceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/UserListRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/DeleteListUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/GetMoviesFromListUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/RemoveMovieFromListUseCase.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/UserListApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/client/RetrofitClient.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/UserListRemoteSourceImpl.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/UserListRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/UserListDetailsResponse.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/UserListItemDto.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/UserListItemRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/shared/GenreMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/AuthenticationRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/UserListRepositoryImpl.kt
  ui/src/main/java/com/amsterdam/ui/components/appBar/DefaultAppBar.kt
  ui/src/main/java/com/amsterdam/ui/navigation/NavGraph.kt
  ui/src/main/java/com/amsterdam/ui/navigation/Route.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/ListDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/ListDetailsScreenRoute.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/component/DeleteListDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/component/GetListDetailsErrorMessage.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/component/MoviesItemsGrid.kt
  ui/src/main/res/drawable-hdpi/alert.png
  ui/src/main/res/drawable-hdpi/no_saved_items.png
  ui/src/main/res/drawable-mdpi/alert.png
  ui/src/main/res/drawable-mdpi/no_saved_items.png
  ui/src/main/res/drawable-xhdpi/alert.png
  ui/src/main/res/drawable-xhdpi/no_saved_items.png
  ui/src/main/res/drawable-xxhdpi/alert.png
  ui/src/main/res/drawable-xxhdpi/no_saved_items.png
  ui/src/main/res/drawable-xxxhdpi/alert.png
  ui/src/main/res/drawable-xxxhdpi/no_saved_items.png
  ui/src/main/res/drawable/ic_remove_item.xml
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsArgs.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsViewModel.kt
Labels: feature

#339 Feature/profile watch history
  ui/src/main/java/com/amsterdam/ui/components/SuccessMediaItemsSection.kt
  ui/src/main/java/com/amsterdam/ui/navigation/NavGraph.kt
  ui/src/main/java/com/amsterdam/ui/navigation/Route.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/ContinueWatchingSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/ProfileScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/HistoryAndRatingSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/LoggedInContent.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/watchHistory/WatchHistoryScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/watchHistory/WatchHistoryScreenRoute.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/SuccessMediaItemsSection.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/watchHistory/WatchHistoryEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/watchHistory/WatchHistoryInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/watchHistory/WatchHistoryUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/watchHistory/WatchHistoryViewModel.kt
Labels: feature

#335 feature/home-list
  app/src/main/java/com/amsterdam/aflami/di/apiServiceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/UserListRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/GetUserListsUseCase.kt
  entity/src/main/java/com/amsterdam/entity/UserList.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/UserListApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/UserListRemoteSourceImpl.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/UserListRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/RemoteUserListDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/RemoteUserListResponse.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/UserListRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/UserListRepositoryImpl.kt
  ui/build.gradle.kts
  ui/src/main/java/com/amsterdam/ui/screens/lists/ListsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/ListsEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/ListsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/ListsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/UserListMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/UserListsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/shared/uiStates/UserListItemUiState.kt
Labels: feature

#346 Fix/details screens slider bug
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
Labels: fix

#353 fix: initial loading is not a shimmer
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
Labels: fix

#355 Test/search flow local data source
  localDatasource/build.gradle.kts
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/CategoryDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/RecentSearchDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createLocalSearchDto.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createLocalTvShowCategoryDto.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createMovie.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createSearchMapping.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/RecentSearchDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/RecentSearchLocalDataSourceImpl.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/CategoryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/RecentSearchLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/WatchHistoryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/utils/createLocalTvShowCategoryDto.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/utils/createMovie.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/RecentSearchLocalSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/LocalSearchDto.kt
  repository/src/main/java/com/amsterdam/repository/repository/RecentSearchRepositoryImpl.kt
Labels: Testing

#357 Feature/add to list
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/Dialog.kt
  domain/src/main/java/com/amsterdam/domain/repository/UserListRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/AddMovieToListUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/CreateNewListUseCase.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/UserListApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImpl.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/UserListRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/AddItemToListResponse.kt
  repository/src/main/java/com/amsterdam/repository/repository/UserListRepositoryImpl.kt
  ui/src/main/java/com/amsterdam/ui/components/AddToListDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/RateDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/UserListUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/myRating/RateDialogInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModelTest.kt
Labels: feature

#361 fix: add default language value to prevent DataStore crash
  localDatasource/src/main/java/com/amsterdam/localdatasource/dataStore/AppPreferencesImpl.kt
Labels: fix

#365 Test/list details
  domain/src/test/java/com/amsterdam/domain/useCase/list/DeleteListUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/GetMoviesFromListUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/RemoveMovieFromListUseCaseTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/util/userListDetails.kt
  repository/src/test/java/com/amsterdam/repository/repository/UserListRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/utils/userListDetails.kt
Labels: Testing

#380 Improve HomeViewModel and make it more testable
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetContinueWatchingScreenDataUseCase.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/continueWatching/ContinueWatchingViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
Labels: refactor

#378 Fix/login screen errors snack bar
  ui/src/main/java/com/amsterdam/ui/screens/login/LoginScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/login/LoginViewModel.kt
Labels: fix

#370 Test: Create list and add movie to list
  domain/src/test/java/com/amsterdam/domain/useCase/list/AddMovieToListUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/CreateNewListUseCaseTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/UserListRepositoryImplTest.kt
Labels: Testing

#375 test: add unit tests for RegisterViewModel with test coverage 100%
  viewModel/src/test/java/com/amsterdam/viewmodel/register/RegisterViewModelTest.kt
Labels: Testing

#382 Fix/enhance recently watched
  ui/src/main/java/com/amsterdam/ui/screens/continueWatching/ContinueWatchingScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/continueWatching/ContinueWatchingViewModel.kt
Labels: fix

#373 Fix/enhance onboarding UI
  ui/src/main/java/com/amsterdam/ui/screens/onBoarding/OnBoardingPage.kt
  ui/src/main/java/com/amsterdam/ui/screens/onBoarding/OnboardingScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/onBoarding/component/NavigationButton.kt
Labels: fix, enhancement

#381 Fix/fix broken test cases in data source
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/AuthenticationRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/ProfileDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/util/CreateRemoteFakeData.kt
Labels: Testing

#389 Fix slider auto-scroll
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
Labels: fix

#388 Make RadioButton clickable with ripple animation effect
  designSystem/src/main/java/com/amsterdam/designsystem/components/RadioButton.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/ContentRestrictionDialog.kt
Labels: fix, enhancement

#387 Delete session type from locally only while making logout.
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/AuthenticationApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/AuthenticationRemoteDataSourceImpl.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/AuthenticationRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/repository/AuthenticationRepositoryImpl.kt
Labels: fix

#390 Fix navigation animation to lists screen when not logged in
  ui/src/main/java/com/amsterdam/ui/screens/lists/ListsScreen.kt
Labels: fix

#395 Fix: Add movie to list loading
  ui/src/main/java/com/amsterdam/ui/components/AddToListDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
Labels: fix

#396 Fix: Clear create new list dialog state after dismiss
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/UserListsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
Labels: fix

#392 Fix/list details bugs
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/utils/apiHandler/responseCall.kt
  ui/src/main/java/com/amsterdam/ui/components/ListItem.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/ListDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/component/MoviesItemsGrid.kt
  ui/src/main/java/com/amsterdam/ui/screens/lists/ListsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/UserListsViewModel.kt
Labels: fix

#391 Fix: Bug31: App Briefly Loads in Dark Theme Before Switching to Saved Light Theme on Launch
  gradle/libs.versions.toml
  ui/build.gradle.kts
  ui/src/main/java/com/amsterdam/ui/application/MainActivity.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/application/ApplicationUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/application/ApplicationViewModel.kt
Labels: fix

#393 Test/add cast view model test
  viewModel/src/test/java/com/amsterdam/viewmodel/CastViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/cast/CastViewModelTest.kt
Labels: Testing

#399 Test/fix broken test cases in repository
  domain/src/test/java/com/amsterdam/domain/useCase/details/GetMovieDetailsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/home/GetMoviesByMoodUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/utils/FakeCategories.kt
  repository/src/main/java/com/amsterdam/repository/repository/AuthenticationRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/CountryRemoteToLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/testFactory/TestMovieCategoryFactory.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/testFactory/TestMovieFactory.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/testFactory/TvShowCategoryTestFactory.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/CountryRemoteToLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/AppPreferencesRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/AuthenticationRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/CategoryRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/CountryRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/MovieRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/ProfileRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/RecentSearchRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/TvShowRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/UserListRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/testFactory/CountryFakeFactory.kt
  repository/src/test/java/com/amsterdam/repository/utils/CreateLocalFakeData.kt
  repository/src/test/java/com/amsterdam/repository/utils/CreateMediaItemDto.kt
  repository/src/test/java/com/amsterdam/repository/utils/createLocalSearchDto.kt
Labels: refactor, Testing

#403 test: add movie details view model test cases
  viewModel/src/test/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModelTest.kt
Labels: Testing

#405 Resolve watch history text and make the card dynamically for large fonts
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/HistoryAndRatingSection.kt
Labels: fix, enhancement

#404 Refactor: Local data source
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/MovieCategoryInterestDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/MovieDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/TvShowCategoryInterestDaoTest.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/dataStore/AuthenticationLocalDataDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/MovieCategoryInterestDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/MovieDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/TvShowCategoryInterestDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/TvShowDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/WatchHistoryDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/CategoryLocalDataDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/CountryLocalDataDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/ProfileLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/RecentSearchLocalDataDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/TvShowLocalDataDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/WatchHistoryLocalDataSourceImpl.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/dataStore/appPreferences/AppDataStorePreferencesTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/CategoryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/CountryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/RecentSearchLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/WatchHistoryLocalDataSourceImplTest.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/utils/apiHandler/responseCall.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/AuthenticationLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/CategoryLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/CountryLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/MovieLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/ProfileLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/RecentSearchLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/TvShowLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/WatchHistoryLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/repository/AuthenticationRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/CountryRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/ProfileRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/RecentSearchRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/repository/AuthenticationRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/CountryRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/MovieRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/RecentSearchRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/TvShowRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImplTest.kt
Labels: refactor

#408 Feature: make app icon change with app theme
  designSystem/src/main/java/com/amsterdam/designsystem/utils/IconManager.kt
  ui/src/main/java/com/amsterdam/ui/application/MainActivity.kt
Labels: feature

#409 Refactor: remove empty manifest files
  designSystem/src/main/AndroidManifest.xml
  localDatasource/src/main/AndroidManifest.xml
  remoteDatasource/src/main/AndroidManifest.xml
  repository/src/main/AndroidManifest.xml
  ui/src/main/AndroidManifest.xml
  viewModel/src/main/AndroidManifest.xml
Labels: chore

#410 Refactor: refactor design system
  designSystem/src/main/java/com/amsterdam/designsystem/DesignSystem.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/TopAppBar.kt
  ui/src/main/java/com/amsterdam/ui/components/appBar/DefaultAppBar.kt
  ui/src/main/java/com/amsterdam/ui/components/appBar/HomeAppBar.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/LoggedInContent.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/NotLoggedInContent.kt
Labels: enhancement

#412 Fix episodes slow loading
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/TvShowsApiService.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/EpisodeRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  ui/src/main/java/com/amsterdam/ui/components/EpisodeCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
Labels: fix, refactor

#415 Fix: fix images across app
  ui/src/main/java/com/amsterdam/ui/components/ProfileImagePlaceholder.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/component/MoviesItemsGrid.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/ActorCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/ReviewCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/myRating/MyRatingScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/ProfileImageSection.kt
Labels: fix

#413 test: add SeriesDetailsViewModelTest
  viewModel/src/test/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModelTest.kt
Labels: Testing

#426 Test/fix broken test cases
  domain/src/test/java/com/amsterdam/domain/useCase/details/GetMovieDetailsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/home/GetMoviesByMoodUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/profile/GetAccountDetailsUseCaseTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/AuthenticationRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImplTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/CastRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/CountryRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/ProductionCompanyRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/ReviewRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/MovieCategoryMappersTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/TvShowCategoryMappersTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/AuthenticationRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/CountryRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/MovieRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/ProfileRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/TvShowRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/utils/CreateMediaItemDto.kt
Labels: Testing

#428 refactor: enhance formatting of user list repository implementation
  repository/src/main/java/com/amsterdam/repository/repository/UserListRepositoryImpl.kt
Labels: refactor

#427 Test/fix broken tests iin mapper
  repository/src/test/java/com/amsterdam/repository/mapper/local/CountryLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/MovieCategoryLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/MovieGenreLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/MovieLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/MovieWithCategoriesLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/RecentSearchLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/TvShowCategoryLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/TvShowGenreLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/TvShowLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/TvShowWithCategoryLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/CategoryRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/GalleryRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/MovieRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/PostersRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/TvShowRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/testFactory/ProductionCompanyDtoFactory.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/testFactory/RemoteCastDtoFactory.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/testFactory/RemoteCategoryDtoFactory.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/testFactory/RemoteCountryDtoFactory.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/testFactory/ReviewDtoFactory.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/testFactory/createRemoteMovieGalleryResponse.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/testFactory/createRemoteMovieItemDto.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/testFactory/createRemoteTvShowItemDto.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/profile/ProfileViewModel.kt
Labels: Testing

#431 feature: implement Let's Play screen UI and basic game logic
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  designSystem/build.gradle.kts
  designSystem/src/main/java/com/amsterdam/designsystem/theme/colors/AflamiColorScheme.kt
  designSystem/src/main/java/com/amsterdam/designsystem/theme/colors/DarkColors.kt
  designSystem/src/main/java/com/amsterdam/designsystem/theme/colors/LigthColors.kt
  domain/src/main/java/com/amsterdam/domain/repository/GameRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/GetAvailableGamesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/GetTotalUserPointsUseCase.kt
  entity/src/main/java/com/amsterdam/entity/Difficulty.kt
  entity/src/main/java/com/amsterdam/entity/Game.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/GameLocalDataSourceImpl.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/GameLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/profile/AccountDetailsLocalDto.kt
  repository/src/main/java/com/amsterdam/repository/repository/GameRepositoryImpl.kt
  ui/build.gradle.kts
  ui/src/main/java/com/amsterdam/ui/components/CategoryCard.kt
  ui/src/main/java/com/amsterdam/ui/components/GameCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/DefficultyLevelData.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/GameTypeData.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/LetsPlayScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/component/DifficultyLevelDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/component/PlayScreenAppBar.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/component/TotalScoreChip.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayViewModel.kt
Labels: feature

#429 Test/fix local datasource broken tests
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/CategoryDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/MovieCategoryInterestDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/MovieDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/TvShowCategoryInterestDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createLocalMovieCategoryDto.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createLocalTvShowCategoryDto.kt
Labels: fix

#432 Fix restoring state bug when we navigate on different tab
  ui/src/main/java/com/amsterdam/ui/application/AflamiApp.kt
Labels: fix

#436 Fix details screens scroll
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
Labels: fix

#437 Fix home screen scroll
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/UpcomingMoviesSection.kt
Labels: fix

#430 refactor: remove companion object from api classes
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/AuthenticationApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/CategoryApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/CountryApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/MovieApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/ProfileApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/TvShowsApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/UserListApiService.kt
Labels: refactor

#441 fix: add success and error snackbars for restriction level updates
  ui/src/main/java/com/amsterdam/ui/screens/profile/ProfileScreen.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/profile/ProfileEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/profile/ProfileViewModel.kt
Labels: fix, refactor

#442 Enhance adaptive grid performance
  ui/src/main/java/com/amsterdam/ui/components/adaptiveGrid.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/UpcomingMoviesSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/companyProductionSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/gallerySection.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/moreLikeSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/component/companyProductionTvShowSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/component/moreTvShowLikeSection.kt
Labels: enhancement

#444 test: refactor test cases for cast viewmodel to be more readable
  viewModel/src/test/java/com/amsterdam/viewmodel/cast/CastViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/utils/TestExtensions.kt
Labels: Testing

#440 fix: show loading indicator for paging append state
  ui/src/main/java/com/amsterdam/ui/screens/search/actorSearch/SearchByActorScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/countrySearch/SearchByCountryScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/countrySearch/components/MoviesVerticalGrid.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/SuccessMediaItemsSection.kt
Labels: fix

#433 Test My Rating View Model
  viewModel/build.gradle.kts
  viewModel/src/main/java/com/amsterdam/viewmodel/myRating/MyRatingUiEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/myRating/MyRatingViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/myRating/MyRatingViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/utils/TestExtensions.kt
Labels: Testing

#447 Refactor/build gradle structure
  app/build.gradle.kts
  build-logic/settings.gradle.kts
  designSystem/build.gradle.kts
  domain/build.gradle.kts
  entity/build.gradle.kts
  gradle/libs.versions.toml
  imageViewer/build.gradle.kts
  localDatasource/build.gradle.kts
  remoteDatasource/build.gradle.kts
  repository/build.gradle.kts
  settings.gradle.kts
  ui/build.gradle.kts
  viewModel/build.gradle.kts
Labels: enhancement, refactor

#450 Refactor watch history and add empty state container
  ui/src/main/java/com/amsterdam/ui/components/SuccessMediaItemsSection.kt
  ui/src/main/java/com/amsterdam/ui/components/grids/SuccessMovieMediaItemsSection.kt
  ui/src/main/java/com/amsterdam/ui/components/grids/SuccessTvShowMediaItemsSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/watchHistory/WatchHistoryScreen.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/watchHistory/WatchHistoryUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/watchHistory/WatchHistoryUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/watchHistory/WatchHistoryViewModel.kt
Labels: enhancement, refactor

#453 Fix: tvshow incorrect behavior in lists
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/UserListRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/GetListMediaItemsFromListUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/GetMoviesFromListUseCase.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/GetListMediaItemsFromListUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/GetMoviesFromListUseCaseTest.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/UserListApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImpl.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImplTest.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/UserListRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/UserListItemRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/UserListRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/repository/UserListRepositoryImplTest.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/ListDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/component/ListDetailsItemsGrid.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/ListDetailsViewModelTest.kt
Labels: fix

#445 Update dao tests and add new tests
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/AccountDetailsDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/BaseDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/CategoryDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/CountryDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/MovieCategoryInterestDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/MovieDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/RecentSearchDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/TvShowCategoryInterestDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/TvShowDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/WatchHistoryDaoTest.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createLocalMovieCategoryDto.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createLocalSearchDto.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createLocalTvShowCategoryDto.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/utils/createMovie.kt
Labels: Testing

#452 Feature/splash screen
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/aflami_splash.xml
  app/src/main/res/drawable/aflami_splash_still.xml
  app/src/main/res/values-night-v31/splash.xml
  app/src/main/res/values-night/splash.xml
  app/src/main/res/values-v31/splash.xml
  app/src/main/res/values/splash.xml
  ui/src/main/java/com/amsterdam/ui/application/AflamiApp.kt
  ui/src/main/java/com/amsterdam/ui/application/GetStartDestination.kt
  ui/src/main/java/com/amsterdam/ui/application/MainActivity.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/application/ApplicationUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/application/ApplicationViewModel.kt
Labels: feature

#462 Feature/game screen
  designSystem/src/main/res/values-ar/strings.xml
  designSystem/src/main/res/values/strings.xml
  ui/src/main/java/com/amsterdam/ui/components/PageIndicator.kt
  ui/src/main/java/com/amsterdam/ui/components/guessGame/GuessPicture.kt
  ui/src/main/java/com/amsterdam/ui/components/selection/AnswerSelectionItem.kt
  ui/src/main/java/com/amsterdam/ui/navigation/NavGraph.kt
  ui/src/main/java/com/amsterdam/ui/navigation/Route.kt
  ui/src/main/java/com/amsterdam/ui/screens/game/GameScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/game/GameScreenRoute.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/LetsPlayScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/onBoarding/OnboardingScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/game/GameEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/game/GameInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/game/GameUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/game/GameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayViewModel.kt
Labels: feature

#457 Feature local game points
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/GamePointsRepository.kt
  localDatasource/src/androidTest/kotlin/com/amsterdam/localdatasource/daos/GamePointsDaoTest.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/AflamiDatabase.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/daos/GamePointsDao.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/GamePointsLocalDataSourceImpl.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/GamePointsLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/GamePointsDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/utils/DatabaseConstants.kt
  repository/src/main/java/com/amsterdam/repository/repository/GamePointsRepositoryImpl.kt
Labels: feature

#463 Feature/game points use case
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  domain/src/main/java/com/amsterdam/domain/exceptions/AflamiException.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/AddGamePointsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/DeductGamePointsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/profile/GetUserPointsUseCase.kt
  domain/src/test/java/com/amsterdam/domain/useCase/game/AddGamePointsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/game/DeductGamePointsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/profile/GetUserPointsUseCaseTest.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/profile/ProfileViewModel.kt
Labels: feature

#459 Feature/create categeory tv show screen
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/MovieRepository.kt
  domain/src/main/java/com/amsterdam/domain/repository/TvShowRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/details/GetMoviesByGenreUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/details/GetTvShowsByGenreUseCase.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/TvShowsApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImpl.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/MovieRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/TvShowsRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowGenreLocalMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  ui/src/androidTest/java/com/amsterdam/ui/ExampleInstrumentedTest.kt
  ui/src/main/java/com/amsterdam/ui/components/CategoryCard.kt
  ui/src/main/java/com/amsterdam/ui/navigation/NavGraph.kt
  ui/src/main/java/com/amsterdam/ui/navigation/Route.kt
  ui/src/main/java/com/amsterdam/ui/screens/categories/CategoriesScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/GenreMovieUiModel.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/GenreTvShowUiModel.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/movies/CategoriesMoviesDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/movies/CategoriesMoviesDetailsScreenRoute.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/tvShow/CategoriesTvShowsDetailsRoute.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/tvShow/CategoriesTvShowsDetailsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categories/CategoriesInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categories/CategoriesUiEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categories/CategoriesUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categories/CategoriesViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/movies/CategoriesMovieDetailsArgs.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/movies/CategoriesMoviesDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/movies/CategoriesMoviesDetailsUiEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/movies/CategoriesMoviesDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/movies/CategoriesMoviesDetailsUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/movies/CategoriesMoviesDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/tvShow/CategoriesTvShowsDetailsArgs.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/tvShow/CategoriesTvShowsDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/tvShow/CategoriesTvShowsDetailsUiEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/tvShow/CategoriesTvShowsDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/tvShow/CategoriesTvShowsDetailsUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/tvShow/CategoriesTvShowsDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/shared/DefaultTvShowGenreUiStates.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/shared/uiStates/TvShowGenreItemUiState.kt
Labels: feature

#464 Feature/implement result screen
  ui/src/main/java/com/amsterdam/ui/navigation/NavGraph.kt
  ui/src/main/java/com/amsterdam/ui/navigation/Route.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/ResultScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/ResultScreenRoute.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/component/CompletionCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/component/GameResultAppBar.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/component/StatCard.kt
  ui/src/main/res/drawable-hdpi/beem_dark.webp
  ui/src/main/res/drawable-hdpi/beem_light.webp
  ui/src/main/res/drawable-mdpi/beem_dark.webp
  ui/src/main/res/drawable-mdpi/beem_light.webp
  ui/src/main/res/drawable-xhdpi/beem_dark.webp
  ui/src/main/res/drawable-xhdpi/beem_light.webp
  ui/src/main/res/drawable-xxhdpi/beem_dark.webp
  ui/src/main/res/drawable-xxhdpi/beem_light.webp
  ui/src/main/res/drawable-xxxhdpi/beem_dark.webp
  ui/src/main/res/drawable-xxxhdpi/beem_light.webp
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/gameEnd/ResultInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameEnd/ResultSideEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameEnd/ResultUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameEnd/ResultViewModel.kt
Labels: feature

#456 Refactor Centralize session and default description
  app/src/main/java/com/amsterdam/aflami/di/apiServiceModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/AuthenticationRepository.kt
  domain/src/main/java/com/amsterdam/domain/repository/TvShowRepository.kt
  domain/src/main/java/com/amsterdam/domain/repository/UserListRepository.kt
  domain/src/main/java/com/amsterdam/domain/repository/WatchHistoryRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/AddMovieToListUseCase.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/MovieApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/ProfileApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/TvShowsApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/UserListApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/client/RetrofitClient.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/ProfileRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/utils/RequiresSessionId.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImplTest.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/MovieRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/ProfileRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/TvShowsRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/UserListRemoteSource.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/ProfileRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/UserListRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/repository/MovieRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/ProfileRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/TvShowRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/UserListRepositoryImplTest.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModelTest.kt
Labels: enhancement, feature, refactor, Testing

#469 Fix/add border to actor card in cast section
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/ActorCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/component/ActorTvShowCard.kt
Labels: fix

#473 Fix Details Screen Loading Flicker
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
Labels: fix

#483 Fix lets play screen UI
  ui/src/main/java/com/amsterdam/ui/components/GameCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/GameTypeData.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/LetsPlayScreen.kt
Labels: fix

#481 Refactor/inject paging source into search country viewmodel
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchPagingSource.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchPagingSourceTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/search/countrySearch/SearchByCountryViewModelTest.kt
Labels: refactor

#484 fix: crash in guess genre of movies
  ui/src/main/java/com/amsterdam/ui/screens/games/guessGenre/GameGenreArgsImpl.kt
Labels: fix

#486 Fix game bugs
  ui/src/main/java/com/amsterdam/ui/screens/games/character/GuessCharacterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessByPoster/GuessByPosterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessGenre/GuessGenreScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/releaseYear/GuessReleaseYearGameScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterQuestionUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterGameViewModel.kt
Labels: fix

#490 Rename local data sources implementation.
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/dataStore/AuthenticationLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/CategoryLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/CountryLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/RecentSearchLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImpl.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/dataStore/appPreferences/AppDataStorePreferencesTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/CategoryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/CountryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/RecentSearchLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImplTest.kt
Labels: refactor

#489 Make the Logout text to be clickable instead of the text beside it.
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/SettingsDialog.kt
Labels: fix

#491 Refactor: Ensure RecentSearchItem handles long titles without hiding cancel icon
  ui/src/main/java/com/amsterdam/ui/components/RecentSearchItem.kt
Labels: fix

#493 Fix/game feature
  designSystem/src/main/java/com/amsterdam/designsystem/theme/colors/LigthColors.kt
  domain/src/main/java/com/amsterdam/domain/exceptions/AflamiException.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/character/GenerateCharacterQuestionsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/character/SubmitCharacterAnswerUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/guessByPoster/DoGuessMovieByPosterHintUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/guessByPoster/GenerateMoviePosterQuestionUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/guessByPoster/SubmitGuessMovieByPosterAnswerUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/releaseYear/SubmitGuessReleaseYearAnswerUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/whichGenre/SubmitGuessMovieGenreAnswerUseCase.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataDataSourceImpl.kt
  ui/src/main/java/com/amsterdam/ui/components/guessGame/AdaptiveAnswersColumn.kt
  ui/src/main/java/com/amsterdam/ui/navigation/NavigationManager.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/character/GuessCharacterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessByPoster/GuessByPosterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessGenre/GuessGenreScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/releaseYear/GuessReleaseYearGameScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/LetsPlayScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/ResultScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/component/NotEnoughPointsDialog.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/game/whichGenre/GenreGameEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/game/whichGenre/GenreGameInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/game/whichGenre/GenreGameUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/game/whichGenre/GuessGenreViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterGameEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearGameEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayViewModel.kt
Labels: refactor

#498 Update README.md
  README.md
Labels: chore

#499 Test/remote data source coverage
  .github/workflows/test_coverage.yml
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  remoteDatasource/build.gradle.kts
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/AuthenticationRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/CategoryRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/CountryRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/PeopleRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImpl.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/AuthenticationRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/CategoryRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/CountryRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/PeopleRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/ProfileRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/util/CreateRemoteFakeData.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/util/MovieTestFactory.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/util/TvShowsTestFactory.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/util/userListDetails.kt
Labels: refactor, Testing

#503 Handle local data sources tests
  localDatasource/build.gradle.kts
  localDatasource/src/test/java/com/amsterdam/localdatasource/dataStore/AppPreferencesImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/dataStore/AuthenticationLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/dataStore/BasePreferencesTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/dataStore/appPreferences/AppDataStorePreferencesTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/CategoryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/CountryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/GameLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/ProfileLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/RecentSearchLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/roomDataBase/datasource/WatchHistoryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/utils/createMovie.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/utils/createTvShow.kt
Labels: refactor, Testing

#487 refactor: remove continue on error from test_coverage workflow
  .github/workflows/test_coverage.yml
  viewModel/build.gradle.kts
Labels: fix, ci

#505 Feature/add linter for remote data source API calls
  app/build.gradle.kts
  gradle/libs.versions.toml
  lint-rules/.gitignore
  lint-rules/build.gradle.kts
  lint-rules/src/main/java/com/amsterdam/lint_rules/AflamiIssueRegistry.kt
  lint-rules/src/main/java/com/amsterdam/lint_rules/ApiCallWrapperDetector.kt
  lint-rules/src/main/resources/META-INF/services/com.android.tools.lint.client.api.IssueRegistry
  remoteDatasource/build.gradle.kts
  settings.gradle.kts
Labels: feature

#521 Fix and improve bottom navigation tab switching logic
  ui/src/main/java/com/amsterdam/ui/application/AflamiApp.kt
  ui/src/main/java/com/amsterdam/ui/components/bottomNavigation/BottomNaviagtion.kt
  ui/src/main/java/com/amsterdam/ui/navigation/NavigationManager.kt
Labels: fix, refactor

#522 Refactor Mood in domain
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetMoviesByMoodUseCase.kt
  domain/src/main/java/com/amsterdam/domain/utils/Mood.kt
  domain/src/test/java/com/amsterdam/domain/useCase/home/GetMoviesByMoodUseCaseTest.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/mapper/MoodMapper.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/model/CardMood.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/MoodPickerSection.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/home/HomeViewModelTest.kt
Labels: refactor

#528 Remove the redundant response call and use other one with default value
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/client/RetrofitClient.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/CategoryRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/CountryRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/PeopleRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/ProfileRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/UserListRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/utils/apiHandler/responseCall.kt
Labels: refactor

#518 fix: mood picker texts overlapping for all font sizes
  ui/src/main/java/com/amsterdam/ui/screens/home/component/MoodPickerCard.kt
Labels: fix

#525 Rename AppPreferences to AppLocalPreferences
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/dataStore/AppLocalPreferencesDataStore.kt
  localDatasource/src/test/java/com/amsterdam/localdatasource/dataStore/AppLocalPreferencesDataStoreTest.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/AppLocalPreferences.kt
  repository/src/main/java/com/amsterdam/repository/repository/AppPreferencesRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/CountryRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/repository/AppPreferencesRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/CountryRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImplTest.kt
Labels: refactor

#532 refactor: add `TextWithClickablePart` composable
  designSystem/src/main/java/com/amsterdam/designsystem/components/TextWithClickablePart.kt
  ui/src/main/java/com/amsterdam/ui/screens/login/LoginScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/login/components/LoginBackground.kt
Labels: fix

#531 feature: implement in-memory game session tracking
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/GameRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/AddPointsToGameUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/AddSecondToGameTimeUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/CreateGameSessionIdUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/GetCollectedPointsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/GetSpentSecondsUseCase.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/inMemory/GameInMemoryDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/GameSessionLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/repository/GameRepositoryImpl.kt
  ui/src/main/java/com/amsterdam/ui/navigation/NavigationManager.kt
  ui/src/main/java/com/amsterdam/ui/navigation/Route.kt
  ui/src/main/java/com/amsterdam/ui/screens/gameResult/ResultScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/character/GuessCharacterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessByPoster/GuessByPosterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessGenre/GuessGenreScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/releaseYear/GuessReleaseYearGameScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/GameResultArgsImpl.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/GameResultArgs.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/GameResultViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/ResultScreenData.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/ResultSideEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessWhichGenre/GenreGameUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessWhichGenre/GuessGenreViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayUiState.kt
Labels: refactor

#516 Fix/base mdeia card type over flow
  ui/src/main/java/com/amsterdam/ui/components/BaseCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/tvShow/CategoriesTvShowsDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/UpcomingMoviesSection.kt
Labels: fix

#501 test: add let's play view model test cases
  viewModel/src/test/java/com/amsterdam/viewmodel/letsPlay/LetsPlayViewModelTest.kt
Labels: Testing

#526 Make getTrendingPeople private
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/PeopleRemoteDataSourceImpl.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/PeopleRemoteDataSourceImplTest.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/PeopleRemoteDataSource.kt
Labels: fix

#535 refactor/rename-functions-conatin-with-not--null-
  domain/src/main/java/com/amsterdam/domain/repository/GameRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/guessByPoster/GenerateMoviePosterQuestionUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/releaseYear/GenerateMovieReleaseYearQuestionsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/whichGenre/GenerateMovieGenreQuestionsUseCase.kt
  domain/src/test/java/com/amsterdam/domain/useCase/game/guessByPoster/GenerateMoviePosterQuestionsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/game/releaseYear/GenerateMovieReleaseYearQuestionsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/game/whichGenre/GenerateMovieGenreQuestionsUseCaseTest.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImpl.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImplTest.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/MovieRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/repository/GameRepositoryImpl.kt
Labels: refactor

#530 Rename user list
  app/src/main/java/com/amsterdam/aflami/di/apiServiceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/WishListRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/CreateNewListUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/DeleteListUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/GetListMediaItemsFromListUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/GetUserListsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/GetWishListsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/RemoveMovieFromListUseCase.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/AddMovieToListUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/CreateNewListUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/DeleteListUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/GetListMediaItemsFromListUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/GetUserListsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/GetWishListsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/RemoveMovieFromListUseCaseTest.kt
  entity/src/main/java/com/amsterdam/entity/WishList.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/WishListApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/client/RetrofitClient.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/WishListRemoteDataSourceImpl.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/WishListRemoteDataSourceImplTest.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/WishListRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/WishListDetailsRemoteResponse.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/WishListItemRemoteDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/WishListRemoteDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/WishListRemoteResponse.kt
  repository/src/main/java/com/amsterdam/repository/mapper/UserListMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/WishListItemMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/WishListMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/WishListRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/repository/WishListRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/utils/userListDetails.kt
  ui/src/main/java/com/amsterdam/ui/components/movieAndTvShowDetails/AddToListDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/lists/ListsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/lists/components/ListItem.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/ListsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/UserListMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/WishListMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/lists/WishListsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/WishListUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/shared/uiStates/WishListItemUiState.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/lists/WishListsViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModelTest.kt
Labels: refactor

#540 Fix/watch history screen bugs
  ui/src/main/java/com/amsterdam/ui/components/NoDataContainer.kt
  ui/src/main/java/com/amsterdam/ui/screens/watchHistory/WatchHistoryScreen.kt
Labels: fix, enhancement

#544 fix: game crash and remove unnecessary mapping
  domain/src/main/java/com/amsterdam/domain/useCase/game/GetAvailableGamesUseCase.kt
  domain/src/test/java/com/amsterdam/domain/useCase/game/GetAvailableGamesUseCaseTest.kt
  entity/src/main/java/com/amsterdam/entity/Game.kt
  ui/src/main/java/com/amsterdam/ui/screens/gameResult/ResultScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/GameTypeData.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/LetsPlayScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/GameResultViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/ResultSideEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessWhichGenre/GuessGenreViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/letsPlay/LetsPlayViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/letsPlay/LetsPlayViewModelTest.kt
Labels: fix

#539 Test/repositories mapper
  repository/src/main/java/com/amsterdam/repository/mapper/TvShowWatchHistoryMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/UserRatedMovieMapper.kt
  repository/src/test/java/com/amsterdam/repository/mapper/AccountDetailsMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/CastMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/CountryMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/EpisodeMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/GalleryMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/MovieCategoryMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/MovieDetailsMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/MovieGenreMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/MovieMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/MovieWatchHistoryMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/MovieWithCategoriesMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/PeopleMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/ProductionCompanyMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/RecentSearchMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/RestrictionLevelMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/ReviewMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/SeasonMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/SessionTypeMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/TvShowCategoryMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/TvShowDetailsMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/TvShowGenreMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/TvShowMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/TvShowRateMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/TvShowWatchHistoryMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/TvShowWithCategoriesMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/UserListItemMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/UserListMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/UserRatedMovieMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/CountryLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/MovieGenreLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/MovieLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/MovieWithCategoriesLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/RecentSearchLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/TvShowCategoryLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/TvShowLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/local/TvShowWithCategoriesLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/CastRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/CountryRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/GalleryRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/MovieRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/ProductionCompanyRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remote/ReviewRemoteMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/CountryRemoteToLocalMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/MovieCategoryMappersTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/MovieDetailsMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/RemoteToLocalCountryMappersTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/RemoteToLocalMovieMappersTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/RemoteToLocalTvShowMappersTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/TvShowCategoryMappersTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/TvShowDetailsMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/testFactory/RemoteCategoryDto.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/testFactory/RemoteCountryDto.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/testFactory/RemoteMovieDetailsResponse.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/testFactory/RemoteMovieItemDto.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/testFactory/RemoteTvShowItemDto.kt
  repository/src/test/java/com/amsterdam/repository/mapper/remoteToLocal/testFactory/TvShowDetailsRemoteResponse.kt
Labels: Testing

#507 Refactor/enhance repository
  repository/src/main/java/com/amsterdam/repository/datasource/local/AuthenticationLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/CategoryLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/GameLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/MovieLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/RecentSearchLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/WatchHistoryLocalDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/CategoryRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/MovieRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/TvShowsRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/WishListRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/CastAndCrewRemoteResponse.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/CastRemoteDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/MovieItemRemoteDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/ProductionCompanyRemoteDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/ProductionCompanyRemoteResponse.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/RatedSerializer.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/TvShowItemRemoteDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/VideoRemoteDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/VideoRemoteResponse.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/WishListDetailsRemoteResponse.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/WishListRemoteResponse.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/authentication/DeleteSessionRemoteDto.kt
  repository/src/main/java/com/amsterdam/repository/mapper/CastMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/CountryMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/MovieCategoryMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/MovieMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/MovieWatchHistoryMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/MovieWithCategoriesMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/ProductionCompanyMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/RecentSearchMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/RestrictionLevelMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/SeasonMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/TvShowCategoryMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/TvShowDetailsMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/TvShowGenreMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/TvShowMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/TvShowRateMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/TvShowWatchHistoryMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/TvShowWithCategoriesMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/UserRatedMovieMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/WishListItemMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/AppPreferencesRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/AuthenticationRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/GameRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/RecentSearchRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/WishListRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/security/CryptoManager.kt
  repository/src/main/java/com/amsterdam/repository/security/CryptoManagerImpl.kt
  repository/src/main/java/com/amsterdam/repository/utils/CryptoManagerExtensions.kt
Labels: refactor

#543 Feature: check is movie in list in movie details
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/Dialog.kt
  designSystem/src/main/res/drawable/ic_sort.xml
  domain/src/main/java/com/amsterdam/domain/repository/WishListRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/CheckIsMovieInListUseCase.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/CheckIsMovieInListUseCaseTest.kt
  remoteDatasource/src/androidTest/java/com/amsterdam/remotedatasource/ExampleInstrumentedTest.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/WishListApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/WishListRemoteDataSourceImpl.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/WishListRemoteDataSourceImplTest.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/WishListRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/WishListMovieItemStatusRemoteResponse.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/WishListRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/mapper/WishListItemMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/WishListMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/WishListRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/utils/userListDetails.kt
  ui/src/main/java/com/amsterdam/ui/components/ProfileImagePlaceholder.kt
  ui/src/main/java/com/amsterdam/ui/components/appBar/DefaultAppBar.kt
  ui/src/main/java/com/amsterdam/ui/components/movieAndTvShowDetails/ReviewCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/AddToListDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/ProfileImageSection.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/build.gradle.kts
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/WishListUiState.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModelTest.kt
Labels: feature

#546 Display title in game result app bar
  ui/src/main/java/com/amsterdam/ui/screens/gameResult/ResultScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/gameResult/component/GameResultAppBar.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/GameResultViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/ResultUiState.kt
Labels: fix, enhancement

#547 refactor: rename People to Character
  app/src/main/java/com/amsterdam/aflami/di/apiServiceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/character/GenerateCharacterQuestionsUseCase.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/api/CharacterApiService.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/client/RetrofitClient.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/CharacterRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/PeopleRemoteDataSourceImpl.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/CharacterRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/PeopleRemoteDataSourceImplTest.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/CharacterRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/datasource/remote/PeopleRemoteDataSource.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/RemoteCharacterItemDto.kt
  repository/src/main/java/com/amsterdam/repository/dto/remote/RemoteCharacterResponse.kt
  repository/src/main/java/com/amsterdam/repository/mapper/CharacterMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/PeopleMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/GameRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/mapper/CharacterMapperTest.kt
Labels: refactor

#549 feature: add score on character guess game
  ui/src/main/java/com/amsterdam/ui/screens/games/character/GuessCharacterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/component/GameScoreCircle.kt
Labels: enhancement

#548 fix: move logic of determining game victory to use case
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  domain/src/main/java/com/amsterdam/domain/useCase/game/EvaluateWinConditionUseCase.kt
  domain/src/test/java/com/amsterdam/domain/useCase/game/EvaluateWinConditionUseCaseTest.kt
  ui/src/main/java/com/amsterdam/ui/screens/gameResult/ResultScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/gameResult/component/CompletionCard.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/GameResultViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/gameResult/ResultUiState.kt
Labels: refactor

#551 refactor: Introduce common game question components and add earned po…
  ui/src/main/java/com/amsterdam/ui/screens/games/character/GuessCharacterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/component/GameQuestionWithImage.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/component/GameQuestionWithTitle.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/component/GameScoreCircle.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/component/GuessTitle.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/component/QuestionImageWithScore.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessByPoster/GuessByPosterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessGenre/GuessGenreScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/releaseYear/GuessReleaseYearGameScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessWhichGenre/GenreGameUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessWhichGenre/GuessGenreViewModel.kt
Labels: feature, refactor

#552 refactor: remove NotLoggedIn status and return null instead
  domain/src/main/java/com/amsterdam/domain/repository/AuthenticationRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/authentication/GetsSessionType.kt
  domain/src/main/java/com/amsterdam/domain/utils/SessionType.kt
  repository/src/main/java/com/amsterdam/repository/mapper/SessionTypeMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/AuthenticationRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/mapper/SessionTypeMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/AuthenticationRepositoryImplTest.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/application/ApplicationViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/profile/ProfileViewModel.kt
Labels: refactor

#477 Test/add category test cases
  domain/src/test/java/com/amsterdam/domain/useCase/details/GetMoviesByGenreUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/details/GetTvShowsByGenreUseCaseTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/MovieRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/TvShowRepositoryImplTest.kt
  ui/src/main/java/com/amsterdam/ui/screens/categories/CategoriesScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categories/CategoriesUiEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categories/CategoriesViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/categories/CategoriesMoviesDetailsViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/categories/CategoriesTvShowsDetailsViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/categories/CategoriesViewModelTest.kt
Labels: refactor, Testing

#557 Fix: fix rating
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  ui/src/main/java/com/amsterdam/ui/components/movieAndTvShowDetails/RateDialog.kt
Labels: fix

#554 Fix series details UI issues
  designSystem/src/main/java/com/amsterdam/designsystem/components/chip/Chip.kt
  ui/src/main/java/com/amsterdam/ui/components/movieAndTvShowDetails/PlayButton.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
Labels: fix

#556 Refactor/handle network error in games
  ui/src/main/java/com/amsterdam/ui/screens/games/character/GuessCharacterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessByPoster/GuessByPosterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessGenre/GuessGenreScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/releaseYear/GuessReleaseYearGameScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessCharacterGame/GuessCharacterUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessMovieByPosterGame/GuessMovieByPosterUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearGameViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessReleseDateGame/GuessReleaseYearUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessWhichGenre/GenreGameInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessWhichGenre/GenreGameUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/guessWhichGenre/GuessGenreViewModel.kt
Labels: refactor

#537 refactor/usecase screen naming
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/WishListRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingDataUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingMoviesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingTvShowsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetHomeScreenDataUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/list/GetListMediaItemsFromListUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/mood/GetMoviesByMoodUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/popular/GetPopularMoviesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/popular/GetPopularTvShowsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/topRated/GetTopRatedDataUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/topRated/GetTopRatedMoviesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/topRated/GetTopRatedTvShowsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/upcoming/GetUpcomingMoviesUseCase.kt
  domain/src/test/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingDataUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingMoviesUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingTvShowsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/home/GetHomeScreenDataUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/list/GetListMediaItemsFromListUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/mood/GetMoviesByMoodUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/popular/GetPopularMoviesUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/popular/GetPopularTvShowsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/topRated/GetTopRatedDataUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/topRated/GetTopRatedMoviesUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/topRated/GetTopRatedTvShowsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/upcoming/GetUpcomingMoviesUseCaseTest.kt
  repository/src/main/java/com/amsterdam/repository/repository/WishListRepositoryImpl.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/continueWatching/ContinueWatchingViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/topRated/TopRatedViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/utils/HomeData.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/watchHistory/WatchHistoryViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/home/HomeViewModelTest.kt
Labels: refactor

#559 refactor: remove redundant Box in game screens
  ui/src/main/java/com/amsterdam/ui/screens/games/component/GuessTitle.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessByPoster/GuessByPosterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessGenre/GuessGenreScreen.kt
Labels: refactor

#555 Use logger to track errors
  app/src/main/java/com/amsterdam/aflami/AppLogger.kt
  app/src/main/java/com/amsterdam/aflami/LoggerInitializer.kt
  app/src/main/java/com/amsterdam/aflami/di/LoggerModule.kt
  domain/src/main/java/com/amsterdam/domain/logger/LogManager.kt
  domain/src/main/java/com/amsterdam/domain/logger/Loggable.kt
  domain/src/main/java/com/amsterdam/domain/logger/Logger.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/client/RetrofitClient.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/CharacterRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/MovieRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/TvRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/datasource/WishListRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/utils/apiHandler/responseCall.kt
Labels: enhancement, refactor

#553 Refactor/preload fonts
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/arrays.xml
Labels: enhancement, refactor

#563 fix: turn all arabic digits to english and fix plurals
  ui/src/main/java/com/amsterdam/ui/components/RatingChip.kt
  ui/src/main/java/com/amsterdam/ui/screens/gameResult/ResultScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/component/GuessCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/component/DifficultyLevelDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/letsPlay/component/TotalScoreChip.kt
  ui/src/main/java/com/amsterdam/ui/screens/lists/components/ListItem.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/AddToListDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/ProfileInfoSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/mappers/FormatSeasonText.kt
  ui/src/main/java/com/amsterdam/ui/utils/StringWithEnglishDigits.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
Labels: fix

#523 Refactor/ Move not entities to domain layer as output classes
  domain/src/main/java/com/amsterdam/domain/repository/WatchHistoryRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingDataUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingMoviesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingTvShowsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/mood/GetMoviesByMoodUseCase.kt
  domain/src/main/java/com/amsterdam/domain/utils/Mood.kt
  domain/src/main/java/com/amsterdam/domain/utils/MovieWatchHistory.kt
  domain/src/main/java/com/amsterdam/domain/utils/TvShowWatchHistory.kt
  domain/src/test/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingDataUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingMoviesUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/continueWatching/GetContinueWatchingTvShowsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/details/GetTvShowDetailsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/mood/GetMoviesByMoodUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/utils/FakeTvShows.kt
  entity/src/main/java/com/amsterdam/entity/category/MovieGenre.kt
  entity/src/main/java/com/amsterdam/entity/category/TvShowGenre.kt
  repository/src/main/java/com/amsterdam/repository/mapper/MovieWatchHistoryMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/TvShowWatchHistoryMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImpl.kt
  repository/src/test/java/com/amsterdam/repository/mapper/MovieWatchHistoryMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/mapper/TvShowWatchHistoryMapperTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/utils/CreateMediaItemDto.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/GenreTvShowUiModel.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/movies/CategoriesMoviesDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/tvShow/CategoriesTvShowsDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/mapper/MoodMapper.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/PopularSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/UpcomingMoviesSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/filterDialog/FilterDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/filterDialog/genre/MovieGenreMapper.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/filterDialog/genre/TvShowGenreMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/continueWatching/ContinueWatchingUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/continueWatching/ContinueWatchingViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsStateMapper.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/home/HomeViewModelTest.kt
Labels: refactor

#588 fix: update plural string format for episodes
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
Labels: fix

#590 Fix: fix blur
  imageViewer/src/main/java/com/amsterdam/imageviewer/ui/SafeImageView.kt
  ui/src/main/java/com/amsterdam/ui/screens/cast/CastScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/movies/CategoriesMoviesDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/tvShow/CategoriesTvShowsDetailsScreen.kt
Labels: fix

#593 readme/add-image-viewer
  README.md
Labels: documentation

#596 Refactor and unify paging method in categories
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/movies/CategoriesMoviesDetailsPagingSource.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/movies/CategoriesMoviesDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/tvShow/CategoriesTvShowDetailsPagingSource.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/tvShow/CategoriesTvShowsDetailsViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/categories/CategoriesMoviesDetailsViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/categories/CategoriesTvShowsDetailsViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/categories/CategoriesViewModelTest.kt
Labels: refactor

#599 Use old paging function in search and handle the correct exception in paging
  viewModel/src/main/java/com/amsterdam/paging/PagingSource.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchPagingSource.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchPagingSource.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/topRated/TopRatedViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/ListDetailsViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchPagingSourceTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchPagingSourceTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/search/countrySearch/SearchByCountryViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/topRated/TopRatedViewModelTest.kt
Labels: fix, refactor

#598 refactor: rename interaction listener in all files in UI
  ui/src/main/java/com/amsterdam/ui/screens/cast/CastScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/categories/CategoriesScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/categoriesDetails/movies/CategoriesMoviesDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/gameResult/ResultScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/character/GuessCharacterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/PopularSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/listDetails/ListDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/lists/ListsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/myRating/MyRatingScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
Labels: refactor

#601 refactor paging source creation in view models
  domain/src/main/java/com/amsterdam/domain/useCase/list/RemoveMovieFromListUseCase.kt
  viewModel/src/main/java/com/amsterdam/paging/PagingSource.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/movies/CategoriesMoviesDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/categoriesDetails/tvShow/CategoriesTvShowsDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/continueWatching/ContinueWatchingViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/listDetails/ListDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/topRated/TopRatedViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/watchHistory/WatchHistoryViewModel.kt
Labels: refactor

#602 Fix/text filed cursor color
  designSystem/src/main/java/com/amsterdam/designsystem/components/TextField.kt
Labels: fix

#603 Fix/fix blur radius
  gradle/libs.versions.toml
  imageViewer/src/main/java/com/amsterdam/imageviewer/coil/SafetyBlurTransformation.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/util/OpenGLBlurProcessor.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/BlurredMediaPoster.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/SuccessMediaItemsSection.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
Labels: fix

#605 Use the keyword in UI state instead of another variable in search by keyword view model
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
Labels: refactor

#608 Resolve duration spacing in strings.
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
Labels: fix

#609 Fix rating stars spacing
  ui/src/main/java/com/amsterdam/ui/components/RatingBar.kt
  ui/src/main/java/com/amsterdam/ui/components/movieAndTvShowDetails/RateDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/filterDialog/FilterDialog.kt
Labels: fix

#611 fix: fix must login in dialog button width
  ui/src/main/java/com/amsterdam/ui/components/MustLoginDialog.kt
Labels: fix

#612 Fix dialog visibility problem
  ui/src/main/java/com/amsterdam/ui/screens/games/character/GuessCharacterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessByPoster/GuessByPosterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/guessGenre/GuessGenreScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/games/releaseYear/GuessReleaseYearGameScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/lists/ListsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/profile/components/LoggedInContent.kt
Labels: fix

#616 Fix stars size for all screens sizes
  ui/src/main/java/com/amsterdam/ui/components/RatingBar.kt
  ui/src/main/java/com/amsterdam/ui/components/movieAndTvShowDetails/RateDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/filterDialog/FilterDialog.kt
Labels: fix
