Repository Amsterdam-Team/Aflami, pull requests merged in 2025-07, with the labels that each got.

#3 Add strings to design system
  designSystem/src/main/res/values-ar/strings.xml
  designSystem/src/main/res/values/strings.xml
Labels: feature

#5 Add required typography for designSystem
  designSystem/build.gradle.kts
  designSystem/src/main/java/com/example/designsystem/AflamiTheme.kt
  designSystem/src/main/java/com/example/designsystem/theme/textStyle/AflamiTextStyle.kt
  designSystem/src/main/java/com/example/designsystem/theme/textStyle/DefaultTextStyle.kt
  designSystem/src/main/res/font/nicomoji_regular.ttf
  designSystem/src/main/res/font/poppins_medium.ttf
  designSystem/src/main/res/font/poppins_regular.ttf
  designSystem/src/main/res/font/poppins_semibold.ttf
Labels: feature

#11 Resolve problem of removing aflami theme.
  designSystem/src/main/java/com/example/designsystem/components/CustomRadioButton.kt
  designSystem/src/main/java/com/example/designsystem/theme/AflamiTheme.kt
  designSystem/src/main/java/com/example/designsystem/theme/AppTheme.kt
Labels: bug

#24 Updated AflamiPreview
  designSystem/src/main/java/com/example/designsystem/utils/AflamiPreview.kt
Labels: enhancement

#29 Added Icon component
  designSystem/src/main/java/com/example/designsystem/components/Icon.kt
Labels: feature

#16 Feature/add category card
  designSystem/src/main/java/com/example/designsystem/components/CategoryCard.kt
Labels: feature

#33 Add HorizontalDivider and VerticalDivider components
  designSystem/src/main/java/com/example/designsystem/components/divider/HorizontalDivider.kt
  designSystem/src/main/java/com/example/designsystem/components/divider/VerticalDivider.kt
Labels: feature

#28 Added text component
  designSystem/src/main/java/com/example/designsystem/components/Text.kt
Labels: feature

#30 Add App Bar Components
  designSystem/src/main/java/com/example/designsystem/components/IconButton.kt
  designSystem/src/main/java/com/example/designsystem/components/appBar/DefaultAppBar.kt
  designSystem/src/main/java/com/example/designsystem/components/appBar/HomeAppBar.kt
  designSystem/src/main/java/com/example/designsystem/components/appBar/TopAppBar.kt
  designSystem/src/main/res/drawable-hdpi/app_logo.png
  designSystem/src/main/res/drawable-mdpi/app_logo.png
  designSystem/src/main/res/drawable-xhdpi/app_logo.png
  designSystem/src/main/res/drawable-xxhdpi/app_logo.png
  designSystem/src/main/res/drawable-xxxhdpi/app_logo.png
  designSystem/src/main/res/drawable/ic__back_arrow.xml
Labels: feature

#23 Add Global Search Hub Composable
  designSystem/src/main/java/com/example/designsystem/components/globalSearchHub/GlobalSearchHub.kt
  designSystem/src/main/java/com/example/designsystem/components/globalSearchHub/GlobalSearchHubUI.kt
  designSystem/src/main/java/com/example/designsystem/theme/AppTheme.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/AflamiColorScheme.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/DarkColors.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/LigthColors.kt
Labels: feature

#36 Add Game Card Component
  designSystem/src/main/java/com/example/designsystem/components/gameCard/BlurredContent.kt
  designSystem/src/main/java/com/example/designsystem/components/gameCard/CircularButton.kt
  designSystem/src/main/java/com/example/designsystem/components/gameCard/GameCard.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/AflamiColorScheme.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/DarkColors.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/LigthColors.kt
Labels: feature

#20 Feature/add chip component
  designSystem/src/main/java/com/example/designsystem/components/Chip.kt
Labels: feature

#37 Add Section Title Component
  designSystem/src/main/java/com/example/designsystem/components/SectionTitle.kt
  designSystem/src/main/res/drawable/ic_birthday_cake.xml
Labels: feature

#40 Add Pull Request Write Permission Access
  .github/workflows/pull_request_workflow.yml
Labels: fix

#39 Added base guess card, picture guess card, title guess card
  designSystem/src/main/java/com/example/designsystem/components/guessGame/GuessCard.kt
  designSystem/src/main/java/com/example/designsystem/components/guessGame/GuessPicture.kt
  designSystem/src/main/java/com/example/designsystem/components/guessGame/GuessTitle.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/AflamiColorScheme.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/DarkColors.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/LigthColors.kt
  designSystem/src/main/java/com/example/designsystem/theme/shapes/SkewRectangleShape.kt
  designSystem/src/main/java/com/example/designsystem/utils/Extensions.kt
  designSystem/src/main/res/values-ar/strings.xml
  designSystem/src/main/res/values/strings.xml
Labels: feature

#53 Fix Ci/Cd to add local properties
  .github/workflows/deploy.yml
  .github/workflows/pull_request_workflow.yml
Labels: fix

#58 Feature/add search by country
  domain/src/main/java/com/example/domain/repository/CountryRepository.kt
  domain/src/main/java/com/example/domain/usecase/GetMoviesByCountryUseCase.kt
  domain/src/main/java/com/example/domain/usecase/GetSuggestedCountriesUseCase.kt
  entity/src/main/java/com/example/entity/Country.kt
  ui/src/main/java/com/example/ui/screens/SearchByCountryScreen.kt
Labels: feature

#54 Add EmptyContainer Composable to Design System
  designSystem/src/main/java/com/example/designsystem/components/NoDataContainer.kt
Labels: feature

#62 Feature/repositories mapper
  domain/src/main/java/com/example/domain/repository/CountryRepository.kt
  entity/src/main/java/com/example/entity/Category.kt
  entity/src/main/java/com/example/entity/Country.kt
  entity/src/main/java/com/example/entity/TvShow.kt
  repository/src/main/java/com/example/repository/dataSource/local/CountryDataSource.kt
  repository/src/main/java/com/example/repository/dataSource/local/LocalMovieDataSource.kt
  repository/src/main/java/com/example/repository/dataSource/local/LocalRecentSearchDataSource.kt
  repository/src/main/java/com/example/repository/dto/local/LocalCountryDto.kt
  repository/src/main/java/com/example/repository/dto/local/LocalSearchDto.kt
  repository/src/main/java/com/example/repository/dto/local/LocalTvShowWithSearchDto.kt
  repository/src/main/java/com/example/repository/mapper/CategoryLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/CountryLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/MovieLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/MovieWithCategoryMapper.kt
  repository/src/main/java/com/example/repository/mapper/TvShowLocalMapper.kt
Labels: feature

#64 Add Koin DI Initialization
  app/src/main/java/com/amsterdam/aflami/AflamiApplication.kt
  app/src/main/java/com/amsterdam/aflami/di/appModule.kt
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
Labels: feature

#63 Feature/repository
  domain/build.gradle.kts
  domain/src/main/java/com/example/domain/repository/CountryRepository.kt
  domain/src/main/java/com/example/domain/repository/RecentSearchRepository.kt
  domain/src/main/java/com/example/domain/usecase/GetSuggestedCountriesUseCase.kt
  entity/src/main/java/com/example/entity/Category.kt
  entity/src/main/java/com/example/entity/TvShow.kt
  localDatasource/build.gradle.kts
  localDatasource/src/main/java/com/example/localdatasource/PlaceHolder.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/AflamiDatabase.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/converter/InstantConverter.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/converter/SearchTypeConverter.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/CategoryDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/CountryDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/MovieDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/RecentSearchDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/TvShowDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/CountryDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/LocalCategoryDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/LocalMovieDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/LocalTvShowDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/RecentSearchDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteMovieDatasourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteTvDatasourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/utils/Constant.kt
  repository/build.gradle.kts
  repository/src/main/java/com/example/repository/PlaceHolder.kt
  repository/src/main/java/com/example/repository/datasource/local/CountryDataSource.kt
  repository/src/main/java/com/example/repository/datasource/local/LocalCategoryDataSource.kt
  repository/src/main/java/com/example/repository/datasource/local/LocalMovieDataSource.kt
  repository/src/main/java/com/example/repository/datasource/local/LocalRecentSearchDataSource.kt
  repository/src/main/java/com/example/repository/datasource/local/LocalTvShowDataSource.kt
  repository/src/main/java/com/example/repository/datasource/remote/RemoteMovieDatasource.kt
  repository/src/main/java/com/example/repository/datasource/remote/RemoteTvShowsDatasource.kt
  repository/src/main/java/com/example/repository/dto/local/LocalCategoryDto.kt
  repository/src/main/java/com/example/repository/dto/local/LocalCountryDto.kt
  repository/src/main/java/com/example/repository/dto/local/LocalMovieDto.kt
  repository/src/main/java/com/example/repository/dto/local/LocalSearchDto.kt
  repository/src/main/java/com/example/repository/dto/local/LocalTvShowDto.kt
  repository/src/main/java/com/example/repository/dto/local/LocalTvShowWithSearchDto.kt
  repository/src/main/java/com/example/repository/dto/local/MovieCategoryCrossRefDto.kt
  repository/src/main/java/com/example/repository/dto/local/relation/MovieWithCategories.kt
  repository/src/main/java/com/example/repository/dto/local/utils/SearchType.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteMovieItemDto.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteMovieResponse.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteTvShowItemDto.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteTvShowResponse.kt
  repository/src/main/java/com/example/repository/mapper/local/CategoryLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/CountryLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/MovieLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/MovieWithCategoryMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/TvShowLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/RemoteMovieMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/RemoteTvShowMapper.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/RecentSearchRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/TvShowRepositoryImpl.kt
Labels: feature

#70 Feature add GetMoviesByActorUseCase
  domain/src/main/java/com/example/domain/usecase/GetMoviesByActorUseCase.kt
Labels: feature

#71 Add search by country
  app/build.gradle.kts
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  designSystem/src/main/java/com/example/designsystem/components/DropdownMenuItem.kt
  designSystem/src/main/java/com/example/designsystem/components/NoDataContainer.kt
  designSystem/src/main/java/com/example/designsystem/components/NoNetworkContainer.kt
  designSystem/src/main/java/com/example/designsystem/components/globalSearchHub/GlobalSearchHubUI.kt
  designSystem/src/main/res/drawable-hdpi/img_news.png
  designSystem/src/main/res/drawable-hdpi/tour_world_image.png
  designSystem/src/main/res/drawable-mdpi/img_news.png
  designSystem/src/main/res/drawable-mdpi/tour_world_image.png
  designSystem/src/main/res/drawable-xhdpi/img_news.png
  designSystem/src/main/res/drawable-xhdpi/tour_world_image.png
  designSystem/src/main/res/drawable-xxhdpi/img_news.png
  designSystem/src/main/res/drawable-xxhdpi/tour_world_image.png
  designSystem/src/main/res/drawable-xxxhdpi/img_news.png
  designSystem/src/main/res/drawable-xxxhdpi/tour_world_image.png
  designSystem/src/main/res/values-ar/strings.xml
  designSystem/src/main/res/values/strings.xml
  domain/src/main/java/com/example/domain/exceptions/AflamiException.kt
  domain/src/main/java/com/example/domain/usecase/GetSuggestedCountriesUseCase.kt
  domain/src/main/java/com/example/domain/validation/CountryValidator.kt
  domain/src/main/java/com/example/domain/validation/CountryValidatorImp.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/LocalCountryDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteCountryDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteMovieDatasourceImpl.kt
  repository/src/main/java/com/example/repository/datasource/local/LocalCountryDataSource.kt
  repository/src/main/java/com/example/repository/datasource/remote/RemoteCountryDataSource.kt
  repository/src/main/java/com/example/repository/datasource/remote/RemoteMovieDatasource.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteCountryDto.kt
  repository/src/main/java/com/example/repository/mapper/remote/RemoteCountryMapper.kt
  repository/src/main/java/com/example/repository/repository/CountryRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  ui/src/main/java/com/example/ui/screens/searchByCountry/SearchByCountryScreen.kt
  viewModel/build.gradle.kts
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/CountryUiState.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/MovieUiState.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryEffect.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryScreenState.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/mapper/CountryMapper.kt
  viewModel/src/main/java/com/example/viewmodel/search/mapper/MovieMapper.kt
Labels: feature

#75 Handle caching for search
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  designSystem/src/main/java/com/example/designsystem/DesignSystem.kt
  designSystem/src/main/java/com/example/designsystem/components/UpcomingCard.kt
  domain/src/main/java/com/example/domain/repository/RecentSearchRepository.kt
  gradle/libs.versions.toml
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/CategoryDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/CountryDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/MovieDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/RecentSearchDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/LocalCategoryDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/LocalCountryDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/LocalMovieDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/RecentSearchDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteMovieDatasourceImpl.kt
  repository/build.gradle.kts
  repository/src/main/java/com/example/repository/datasource/local/LocalCategoryDataSource.kt
  repository/src/main/java/com/example/repository/datasource/local/LocalMovieDataSource.kt
  repository/src/main/java/com/example/repository/datasource/local/LocalRecentSearchDataSource.kt
  repository/src/main/java/com/example/repository/dto/local/LocalSearchDto.kt
  repository/src/main/java/com/example/repository/mapper/local/RecentSearchMapper.kt
  repository/src/main/java/com/example/repository/repository/CategoryRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/RecentSearchRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/TvShowRepositoryImpl.kt
  ui/src/main/java/com/example/ui/screen/search/SearchScreen.kt
  ui/src/main/java/com/example/ui/screens/SearchByActorScreen.kt
  ui/src/main/java/com/example/ui/screens/search/SearchResoursGetters.kt
  ui/src/main/java/com/example/ui/screens/search/SearchScreen.kt
  ui/src/main/java/com/example/ui/screens/search/sections/RecentSearches.kt
  ui/src/main/java/com/example/ui/screens/search/sections/SuggestionsHub.kt
  ui/src/main/java/com/example/ui/screens/search/sections/filterDialog/FilterDialog.kt
  ui/src/main/java/com/example/ui/screens/search/sections/filterDialog/GenreMapper.kt
  ui/src/main/java/com/example/ui/screens/searchByActor/SearchByActorScreen.kt
  ui/src/main/java/com/example/ui/screens/searchByCountry/SearchByCountryScreen.kt
  viewModel/src/main/java/com/example/viewmodel/BaseViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/searchByActor/SearchByActorScreenState.kt
  viewModel/src/main/java/com/example/viewmodel/searchByActor/SearchByActorUiState.kt
  viewModel/src/main/java/com/example/viewmodel/searchByActor/SearchByActorViewModel.kt
Labels: feature

#83 Fix some UI bugs
  imageViewer/src/main/java/com/example/imageviewer/ui/SafeImageView.kt
  ui/src/main/java/com/example/ui/screens/searchByCountry/SearchByCountryScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/mapper/MovieMapper.kt
Labels: fix

#85 Fix/ Search Bar State and Ratings Fraction
  viewModel/src/main/java/com/example/viewmodel/BaseViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/common/MediaItemUiState.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryViewModel.kt
Labels: fix

#84 fix: enable Apply button in FilterDialog based on filter data
  ui/src/main/java/com/example/ui/screens/search/sections/FilterDialog.kt
  viewModel/src/main/java/com/example/viewmodel/search/SearchUiState.kt
Labels: fix

#90 Fix Search Movies to Load
  remoteDatasource/src/main/java/com/example/remotedatasource/client/Endpoints.kt
Labels: fix

#92 fix: Image viewer
  gradle/libs.versions.toml
  imageViewer/src/main/java/com/example/imageviewer/classification/ClassifierConfig.kt
  imageViewer/src/main/java/com/example/imageviewer/classification/ImageClassifier.kt
  imageViewer/src/main/java/com/example/imageviewer/classification/SFWImageClassifier.kt
  imageViewer/src/main/java/com/example/imageviewer/coil/ImageLoaderFactory.kt
  imageViewer/src/main/java/com/example/imageviewer/coil/SafetyInterceptor.kt
Labels: fix

#96 fix: tests not compiling
  repository/src/androidTest/java/com/example/repository/ExampleInstrumentedTest.kt
  repository/src/test/java/com/example/repository/ExampleUnitTest.kt
  repository/src/test/java/com/example/repository/mapper/local/CategoryLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieWithCategoryMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/RemoteTvShowMapperTest.kt
  viewModel/src/androidTest/java/com/example/viewmodel/ExampleInstrumentedTest.kt
  viewModel/src/test/java/com/example/viewmodel/utils/entityHelper/createMovie.kt
Labels: fix

#98 Fix Ktor client's Url Construction And Improve Remote Datasource Module
  domain/src/main/java/com/example/domain/useCase/GetMoviesByKeywordUseCase.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/Endpoints.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/KtorClient.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteMovieDatasourceImpl.kt
  viewModel/src/main/java/com/example/viewmodel/search/GlobalSearchViewModel.kt
Labels: fix

#100 feature: use cases tests
  domain/build.gradle.kts
  domain/src/test/java/com/example/domain/useCase/GetMovieCategoriesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetMoviesByActorUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetMoviesByCountryUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetMoviesByKeywordUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetSuggestedCountriesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetTvShowByKeywordUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetTvShowCategoriesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/search/AddRecentSearchUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/search/ClearAllRecentSearchesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/search/ClearRecentSearchUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/search/GetRecentSearchesUseCaseTest.kt
  gradle/libs.versions.toml
Labels: feature

#102 Refactor Ktor Client And Interceptor
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/Endpoints.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/Interceptor.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/KtorClient.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteCategoryDatasourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteCountryDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteMovieDatasourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteTvDatasourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/utils/Constant.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/utils/apiHandler/ResponseToResult.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/utils/apiHandler/SafeCall.kt
Labels: refactor

#94 Add No Data Container When No Movies Found By Keyword
  domain/src/main/java/com/example/domain/exceptions/AflamiException.kt
  domain/src/main/java/com/example/domain/useCase/GetMoviesByKeywordUseCase.kt
  domain/src/test/java/com/example/domain/useCase/GetMoviesByKeywordUseCaseTest.kt
  ui/src/main/java/com/example/ui/screens/search/SearchResoursGetters.kt
  ui/src/main/java/com/example/ui/screens/search/SearchScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/GlobalSearchViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/SearchUiState.kt
Labels: fix

#105 Fix TvShows Do Not Load With Current Query When User Change Tab
  viewModel/src/main/java/com/example/viewmodel/search/GlobalSearchViewModel.kt
Labels: fix

#106 Test/implement category repository impl
  gradle/libs.versions.toml
  repository/build.gradle.kts
  repository/src/test/java/com/example/repository/repository/CategoryRepositoryImplTest.kt
Labels: feature

#110 test: add RecentSearchRepositoryImpl tests
  repository/src/test/java/com/example/repository/repository/RecentSearchRepositoryImplTest.kt
Labels: feature

#101 Resolve UI problems in search by country
  ui/src/main/java/com/example/ui/screens/searchByCountry/SearchByCountryScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryEffect.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryViewModel.kt
Labels: fix

#114 Fix/navigate back to global search
  ui/src/main/java/com/example/ui/screens/search/SearchScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/GlobalSearchViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/SearchIntractionListener.kt
Labels: fix, feature

#113 fix: search function of SearchByActor and enhance the logic
  domain/src/main/java/com/example/domain/exceptions/AflamiException.kt
  domain/src/main/java/com/example/domain/useCase/GetMoviesByActorUseCase.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteMovieDatasourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/RemoteTvDatasourceImpl.kt
  ui/src/main/java/com/example/ui/screens/searchByActor/SearchByActorScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/mapper/MovieMapper.kt
  viewModel/src/main/java/com/example/viewmodel/searchByActor/SearchByActorViewModel.kt
Labels: fix, refactor

#120 Fix: no internet container
  remoteDatasource/src/main/java/com/example/remotedatasource/utils/apiHandler/SafeCall.kt
  ui/src/main/java/com/example/ui/screens/search/SearchResoursGetters.kt
  ui/src/main/java/com/example/ui/screens/search/SearchScreen.kt
  ui/src/main/java/com/example/ui/screens/searchByActor/SearchByActorScreen.kt
  ui/src/main/java/com/example/ui/screens/searchByCountry/SearchByCountryScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/GlobalSearchViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/SearchIntractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/search/SearchUiState.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryScreenState.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/searchByActor/SearchByActorInteractionListiner.kt
  viewModel/src/main/java/com/example/viewmodel/searchByActor/SearchByActorViewModel.kt
Labels: fix

#123 Fix/resolve search by country screen UI
  designSystem/src/main/java/com/example/designsystem/components/CenterOfScreenContainer.kt
  ui/src/main/java/com/example/ui/screens/searchByCountry/SearchByCountryScreen.kt
Labels: fix

#124 Refactor/domain refactor
  domain/src/main/java/com/example/domain/common/ContentFilteringExtensions/ContentFilteringExtensions.kt
  domain/src/main/java/com/example/domain/common/ContentFilteringExtensions/FilterByRatingExtensions.kt
  domain/src/main/java/com/example/domain/common/ContentFilteringExtensions/PopularitySorting.kt
  domain/src/main/java/com/example/domain/common/ContentFilteringExtensions/ThrowIfEmpty.kt
  domain/src/main/java/com/example/domain/common/CountryExtensions/FilterByName.kt
  domain/src/main/java/com/example/domain/exceptions/AflamiException.kt
  domain/src/main/java/com/example/domain/repository/CategoryRepository.kt
  domain/src/main/java/com/example/domain/repository/CountryRepository.kt
  domain/src/main/java/com/example/domain/repository/RecentSearchRepository.kt
  domain/src/main/java/com/example/domain/useCase/GetMoviesByActorUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetMoviesByKeywordUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetSuggestedCountriesUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetTvShowByKeywordUseCase.kt
  domain/src/main/java/com/example/domain/validation/CountryValidatorImp.kt
  domain/src/test/java/com/example/domain/useCase/GetMovieCategoriesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetMoviesByActorUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetMoviesByCountryUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetMoviesByKeywordUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetSuggestedCountriesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetTvShowByKeywordUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetTvShowCategoriesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/search/AddRecentSearchUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/search/ClearAllRecentSearchesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/search/ClearRecentSearchUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/search/GetRecentSearchesUseCaseTest.kt
  entity/src/main/java/com/example/entity/Category.kt
  entity/src/main/java/com/example/entity/Movie.kt
  entity/src/main/java/com/example/entity/TvShow.kt
  entity/src/main/java/com/example/entity/common/Categorizable.kt
  entity/src/main/java/com/example/entity/common/PopularitySortable.kt
  entity/src/main/java/com/example/entity/common/RatingFilterable.kt
  viewModel/src/main/java/com/example/viewmodel/search/globalSearch/GlobalSearchViewModel.kt
Labels: refactor

#127 Refactored search by country
  domain/src/main/java/com/example/domain/exceptions/AflamiException.kt
  ui/src/main/java/com/example/ui/screens/searchByCountry/SearchByCountryScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryEffect.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryScreenState.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/mapper/SearchByCountryErrorMapper.kt
  viewModel/src/test/java/com/example/viewmodel/SearchByCountryViewModelTest.kt
Labels: enhancement

#131 Resolve Movie caching problem while searching by country and actor
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/MovieDao.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
Labels: fix

#130 Refactor Ktor Client with safe Call and Centralized JSON Parsing
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/KtorClient.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/CategoryRemoteSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/CountryRemoteSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/MovieRemoteSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/TvRemoteSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/utils/apiHandler/SafeCall.kt
  ui/src/main/java/com/example/ui/application/MainActivity.kt
Labels: refactor

#137 Refactor search by country
  designSystem/src/main/java/com/example/designsystem/components/CenterOfScreenContainer.kt
  designSystem/src/main/java/com/example/designsystem/components/LoadingContainer.kt
  ui/src/main/java/com/example/ui/navigation/NavGraph.kt
  ui/src/main/java/com/example/ui/screens/search/SearchScreen.kt
  ui/src/main/java/com/example/ui/screens/search/searchByCountry/SearchByCountryScreen.kt
  ui/src/main/java/com/example/ui/screens/search/searchByCountry/SearchByCountryScreenRoute.kt
  ui/src/main/java/com/example/ui/screens/search/searchByCountry/components/CountriesDropdownMenu.kt
  ui/src/main/java/com/example/ui/screens/search/searchByCountry/components/CountrySearchField.kt
  ui/src/main/java/com/example/ui/screens/search/searchByCountry/components/ExploreCountries.kt
  ui/src/main/java/com/example/ui/screens/search/searchByCountry/components/MoviesVerticalGrid.kt
  ui/src/main/java/com/example/ui/screens/search/searchByCountry/components/NoMoviesFound.kt
  ui/src/main/java/com/example/ui/screens/searchByActor/SearchByActorScreen.kt
  ui/src/main/java/com/example/ui/screens/searchByCountry/SearchByCountryScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryEffect.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/SearchByCountryViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/searchByKeyword/genre/GenreItemUiState.kt
  viewModel/src/main/java/com/example/viewmodel/utils/Extensions.kt
  viewModel/src/test/java/com/example/viewmodel/SearchByCountryViewModelTest.kt
  viewModel/src/test/java/com/example/viewmodel/utils/entityHelper/createMovie.kt
Labels: enhancement

#142 Fix rotating screen
  designSystem/src/main/java/com/example/designsystem/theme/AflamiTheme.kt
Labels: fix

#134 Refactor/refactor design system
  designSystem/src/main/java/com/example/designsystem/DesignSystem.kt
  designSystem/src/main/java/com/example/designsystem/components/BaseCard.kt
  designSystem/src/main/java/com/example/designsystem/components/CenterOfScreenContainer.kt
  designSystem/src/main/java/com/example/designsystem/components/Chip.kt
  designSystem/src/main/java/com/example/designsystem/components/CustomMoodPickerCard.kt
  designSystem/src/main/java/com/example/designsystem/components/CustomRadioButton.kt
  designSystem/src/main/java/com/example/designsystem/components/CustomSlider.kt
  designSystem/src/main/java/com/example/designsystem/components/DropdownMenuItem.kt
  designSystem/src/main/java/com/example/designsystem/components/EpisodeCard.kt
  designSystem/src/main/java/com/example/designsystem/components/GameCard.kt
  designSystem/src/main/java/com/example/designsystem/components/ListItem.kt
  designSystem/src/main/java/com/example/designsystem/components/MovieCard.kt
  designSystem/src/main/java/com/example/designsystem/components/NoDataContainer.kt
  designSystem/src/main/java/com/example/designsystem/components/NoNetworkContainer.kt
  designSystem/src/main/java/com/example/designsystem/components/RatingChip.kt
  designSystem/src/main/java/com/example/designsystem/components/RecentSearchItem.kt
  designSystem/src/main/java/com/example/designsystem/components/Scaffold.kt
  designSystem/src/main/java/com/example/designsystem/components/TabLayout.kt
  designSystem/src/main/java/com/example/designsystem/components/TextField.kt
  designSystem/src/main/java/com/example/designsystem/components/UpcomingCard.kt
  designSystem/src/main/java/com/example/designsystem/components/appBar/DefaultAppBar.kt
  designSystem/src/main/java/com/example/designsystem/components/bottomNavBar/BottomBarItems.kt
  designSystem/src/main/java/com/example/designsystem/components/bottomNavBar/BottomNavBar.kt
  designSystem/src/main/java/com/example/designsystem/components/buttons/BaseButton.kt
  designSystem/src/main/java/com/example/designsystem/components/buttons/ConfirmButton.kt
  designSystem/src/main/java/com/example/designsystem/components/buttons/FloatingActionButton.kt
  designSystem/src/main/java/com/example/designsystem/components/buttons/OutlinedButton.kt
  designSystem/src/main/java/com/example/designsystem/components/buttons/PlainTextButton.kt
  designSystem/src/main/java/com/example/designsystem/components/gameCard/BlurredContent.kt
  designSystem/src/main/java/com/example/designsystem/components/gameCard/CircularButton.kt
  designSystem/src/main/java/com/example/designsystem/components/globalSearchHub/GlobalSearchHub.kt
  designSystem/src/main/java/com/example/designsystem/components/guessGame/GuessCard.kt
  designSystem/src/main/java/com/example/designsystem/components/guessGame/GuessPicture.kt
  designSystem/src/main/java/com/example/designsystem/components/guessGame/GuessTitle.kt
  designSystem/src/main/java/com/example/designsystem/theme/textStyle/DefaultTextStyle.kt
  ui/src/main/java/com/example/ui/screens/search/sections/filterDialog/FilterDialog.kt
Labels: refactor

#132 refactor: use Koin's singleOf and viewModelOf for DI
  app/src/main/java/com/amsterdam/aflami/di/appModule.kt
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/TvShowRepositoryImpl.kt
Labels: fix

#149 Refactored repository module
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  domain/src/main/java/com/example/domain/repository/RecentSearchRepository.kt
  domain/src/main/java/com/example/domain/useCase/GetMovieCategoriesUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetTvShowCategoriesUseCase.kt
  domain/src/main/java/com/example/domain/useCase/RecentSearchesUseCase.kt
  domain/src/test/java/com/example/domain/useCase/search/AddRecentSearchUseCaseTest.kt
  repository/src/main/java/com/example/repository/dto/remote/ActorSearchItemDto.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteMovieItemDto.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteTvShowItemDto.kt
  repository/src/main/java/com/example/repository/mapper/local/CountryLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/MovieCategoryLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/MovieLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/SearchWithMoviesMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/TvShowCategoryLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/TvShowLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/MovieRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/shared/DtoMapper.kt
  repository/src/main/java/com/example/repository/repository/CategoryRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/CountryRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/RecentSearchRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/TvShowRepositoryImpl.kt
  repository/src/main/java/com/example/repository/utils/RecentSearchHandler.kt
  repository/src/main/java/com/example/repository/utils/RecentSearchHandlerImpl.kt
Labels: fix, refactor

#147 Refactor/local data source
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  localDatasource/build.gradle.kts
  localDatasource/src/androidTest/java/com/example/localdatasource/ExampleInstrumentedTest.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/AflamiDatabase.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/converter/InstantConverter.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/CategoryLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/CountryLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/RecentSearchLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImpl.kt
  localDatasource/src/test/java/com/example/localdatasource/CategoryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/example/localdatasource/CountryLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/example/localdatasource/DummyData.kt
  localDatasource/src/test/java/com/example/localdatasource/ExampleUnitTest.kt
  localDatasource/src/test/java/com/example/localdatasource/MovieLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/example/localdatasource/RecentSearchLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/example/localdatasource/TvShowLocalDataSourceImplTest.kt
Labels: feature, refactor

#158 Handle full path of image url
  repository/src/main/java/com/example/repository/dto/remote/ProductionCompanyDto.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteCastDto.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteCrewDto.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteMovieItemDto.kt
  repository/src/main/java/com/example/repository/dto/remote/RemoteTvShowItemDto.kt
  repository/src/main/java/com/example/repository/dto/remote/movieGallery/GalleryImageDto.kt
  repository/src/main/java/com/example/repository/dto/remote/review/AuthorDetailsDto.kt
  repository/src/main/java/com/example/repository/mapper/remote/CastRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/GalleryRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/MovieRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/ProductionCompanyRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/ReviewRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/TvShowRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remoteToLocal/MovieRemoteLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/remoteToLocal/TvShowRemoteLocalMapper.kt
Labels: fix

#160 Fix Infinte Retry Button Loading
  ui/src/main/java/com/example/ui/screens/search/keywordSearch/SearchScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/keywordSearch/SearchViewModel.kt
Labels: fix

#161 User Category Interest Tracking
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  domain/src/main/java/com/example/domain/repository/MovieRepository.kt
  domain/src/main/java/com/example/domain/repository/TvShowRepository.kt
  domain/src/main/java/com/example/domain/useCase/GetAndFilterMoviesByKeywordUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetAndFilterTvShowsByKeywordUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetMovieDetailsUseCase.kt
  domain/src/main/java/com/example/domain/useCase/IncrementMovieGenreInterestUseCase.kt
  domain/src/main/java/com/example/domain/useCase/IncrementTvShowGenreInterestUseCase.kt
  domain/src/test/java/com/example/domain/useCase/IncrementMovieGenreInterestUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/IncrementTvShowGenreInterestUseCaseTest.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/AflamiDatabase.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/MovieCategoryInterestDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/TvShowCategoryInterestDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/TvShowLocalDataSourceImpl.kt
  repository/src/main/java/com/example/repository/datasource/local/MovieLocalSource.kt
  repository/src/main/java/com/example/repository/datasource/local/TvShowLocalSource.kt
  repository/src/main/java/com/example/repository/dto/local/LocalMovieCategoryInterestDto.kt
  repository/src/main/java/com/example/repository/dto/local/LocalTvShowCategoryInterestDto.kt
  repository/src/main/java/com/example/repository/dto/local/utils/DatabaseContract.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/TvShowRepositoryImpl.kt
Labels: feature

#155 Fix/refactor search by actor
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  ui/src/main/java/com/example/ui/screens/search/actorSearch/SearchByActorScreen.kt
  viewModel/src/main/java/com/example/viewmodel/search/actorSearch/ActorSearchInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/search/actorSearch/ActorSearchUiState.kt
  viewModel/src/main/java/com/example/viewmodel/search/actorSearch/ActorSearchViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/actorSearch/SearchActorEffect.kt
  viewModel/src/main/java/com/example/viewmodel/search/actorSearch/SearchActorInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/search/actorSearch/SearchActorViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/shared/MediaItemUiState.kt
  viewModel/src/test/java/com/example/viewmodel/SearchByActorViewModelTest.kt
  viewModel/src/test/java/com/example/viewmodel/utils/entityHelper/createMovie.kt
Labels: refactor

#138 Feature: Implementing Pagination in search screens
  domain/src/main/java/com/example/domain/repository/MovieRepository.kt
  domain/src/main/java/com/example/domain/repository/TvShowRepository.kt
  domain/src/main/java/com/example/domain/useCase/GetAndFilterMoviesByKeywordUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetAndFilterTvShowsByKeywordUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetMoviesByActorUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetMoviesByCountryUseCase.kt
  gradle/libs.versions.toml
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/MovieRemoteSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/TvRemoteSourceImpl.kt
  repository/src/main/java/com/example/repository/datasource/remote/MovieRemoteSource.kt
  repository/src/main/java/com/example/repository/datasource/remote/TvShowsRemoteSource.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/TvShowRepositoryImpl.kt
  ui/build.gradle.kts
  ui/src/main/java/com/example/ui/screens/search/actorSearch/SearchByActorScreen.kt
  ui/src/main/java/com/example/ui/screens/search/countrySearch/SearchByCountryScreen.kt
  ui/src/main/java/com/example/ui/screens/search/countrySearch/components/MoviesVerticalGrid.kt
  ui/src/main/java/com/example/ui/screens/search/keywordSearch/SearchScreen.kt
  viewModel/build.gradle.kts
  viewModel/src/main/java/com/example/paging/PagingSource.kt
  viewModel/src/main/java/com/example/viewmodel/search/actorSearch/ActorSearchUiState.kt
  viewModel/src/main/java/com/example/viewmodel/search/actorSearch/SearchActorViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/CountrySearchUiState.kt
  viewModel/src/main/java/com/example/viewmodel/search/countrySearch/CountrySearchViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/keywordSearch/SearchUiState.kt
  viewModel/src/main/java/com/example/viewmodel/search/keywordSearch/SearchViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/search/mapper/MediaItemUiStateMapper.kt
  viewModel/src/main/java/com/example/viewmodel/search/mapper/MovieItemUiStateMapper.kt
Labels: feature, refactor

#163 Resolve test errors
  domain/src/test/java/com/example/domain/useCase/GetAndFilterMoviesByKeywordUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetAndFilterTvShowsByKeywordUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetMovieCategoriesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetMoviesByActorUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetMoviesByCountryUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetTvShowCategoriesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/RecentSearchesUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/search/AddRecentSearchUseCaseTest.kt
  localDatasource/src/test/java/com/example/localdatasource/MovieLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/example/localdatasource/TvShowLocalDataSourceImplTest.kt
  repository/src/test/java/com/example/repository/mapper/local/CategoryRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/CountryRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/MovieRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/TvShowRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/repository/CategoryRepositoryImplTest.kt
  repository/src/test/java/com/example/repository/repository/CountryRepositoryImplTest.kt
  repository/src/test/java/com/example/repository/repository/RecentSearchRepositoryImplTest.kt
  viewModel/src/test/java/com/example/viewmodel/SearchByActorViewModelTest.kt
  viewModel/src/test/java/com/example/viewmodel/SearchByCountryViewModelTest.kt
Labels: fix

#162 feature: implement popular movies section in home screen
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  domain/src/main/java/com/example/domain/repository/MovieRepository.kt
  domain/src/main/java/com/example/domain/useCase/GetPopularMoviesUseCase.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/MovieRemoteDataSourceImpl.kt
  repository/src/main/java/com/example/repository/datasource/remote/MovieRemoteSource.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  ui/src/main/java/com/example/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/example/ui/screens/home/HomeScreenRoute.kt
  ui/src/main/java/com/example/ui/screens/home/component/PopularMovieCard.kt
  ui/src/main/java/com/example/ui/screens/home/component/PopularSection.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeEffect.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeUiState.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeUiStateMapper.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeViewModel.kt
Labels: feature

#166 Fix Test Coverage And Migrate To Cover
  .github/workflows/test_coverage.yml
  app/build.gradle.kts
  app/src/androidTest/java/com/amsterdam/aflami/ExampleInstrumentedTest.kt
  blurred/build.gradle.kts
  blurred/src/androidTest/java/com/amsterdam/blurred/ExampleInstrumentedTest.kt
  build-logic/.gitignore
  build.gradle.kts
  designSystem/src/androidTest/java/com/example/designsystem/ExampleInstrumentedTest.kt
  domain/build.gradle.kts
  domain/src/test/java/com/example/domain/useCase/GetMoviesByKeywordUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/GetTvShowByKeywordUseCaseTest.kt
  domain/src/test/java/com/example/domain/useCase/RecentSearchesUseCaseTest.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  localDatasource/build.gradle.kts
  localDatasource/src/test/java/com/example/localdatasource/MovieLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/example/localdatasource/RecentSearchLocalDataSourceImplTest.kt
  localDatasource/src/test/java/com/example/localdatasource/TvShowLocalDataSourceImplTest.kt
  remoteDatasource/build.gradle.kts
  repository/build.gradle.kts
  repository/src/test/java/com/example/repository/mapper/local/CategoryRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/MovieRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/TvShowRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/repository/CategoryRepositoryImplTest.kt
  repository/src/test/java/com/example/repository/repository/CountryRepositoryImplTest.kt
  repository/src/test/java/com/example/repository/repository/RecentSearchRepositoryImplTest.kt
  settings.gradle.kts
  viewModel/build.gradle.kts
  viewModel/src/test/java/com/example/viewmodel/SearchByActorViewModelTest.kt
  viewModel/src/test/java/com/example/viewmodel/SearchByCountryViewModelTest.kt
Labels: fix, refactor

#165 Test/local mappers
  gradle/libs.versions.toml
  repository/build.gradle.kts
  repository/src/test/java/com/example/repository/mapper/local/CategoryRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/CountryLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieCategoryLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieGenreLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieWithCategoriesLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/RecentSearchLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowCategoryLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowGenreLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowWithCategoryLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/testFactory/TestMovieCategoryFactory.kt
  repository/src/test/java/com/example/repository/mapper/local/testFactory/TestMovieFactory.kt
  repository/src/test/java/com/example/repository/mapper/local/testFactory/TvShowCategoryTestFactory.kt
Labels: fix

#168 Feature/migrate from ktor to retrofit
  app/src/main/java/com/amsterdam/aflami/di/appModule.kt
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/serviceModule.kt
  gradle/libs.versions.toml
  remoteDatasource/build.gradle.kts
  remoteDatasource/src/main/java/com/example/remotedatasource/api/CategoryApiService.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/api/CountryApiService.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/api/MovieApiService.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/api/TvShowsApiService.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/KtorClient.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/NetworkClient.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/RetrofitClient.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/CategoryRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/CountryRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/MovieRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/TvRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/CategoryServiceProvider.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/CountryServiceProvider.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/MovieServiceProvider.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/TvShowsServiceProvider.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/implementation/CategoryServiceProviderImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/implementation/CountryServiceProviderImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/implementation/MovieServiceProviderImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/implementation/TvShowsServiceProviderImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/utils/apiHandler/HandleHttpResponse.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/utils/apiHandler/responseCall.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/CategoryRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/CountryRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/MovieRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/TvRemoteDataSourceImplTest.kt
Labels: feature

#174 Feature: Authentication repo
  domain/src/main/java/com/example/domain/exceptions/AflamiException.kt
  domain/src/main/java/com/example/domain/repository/AuthenticationRepository.kt
  domain/src/main/java/com/example/domain/useCase/authentication/LoginWithPasswordUseCase.kt
  domain/src/test/java/com/example/domain/useCase/authentication/LoginWithUsernamePasswordTest.kt
Labels: feature

#175 Test/remote mappers
  repository/src/test/java/com/example/repository/mapper/remote/CastRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/CategoryRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/CountryRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/GalleryRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/MovieRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/PostersRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/ProductionCompanyRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/ReviewRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/TvShowRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/ProductionCompanyDtoFactory.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/RemoteCastDtoFactory.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/RemoteCategoryDtoFactory.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/RemoteCountryDtoFactory.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/ReviewDtoFactory.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/createRemoteMovieGalleryResponse.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/createRemoteMovieItemDto.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/createRemoteTvShowItemDto.kt
Labels: fix

#171 Feature: login screen and viewmodel
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  designSystem/src/main/java/com/example/designsystem/components/buttons/ButtonDefaults.kt
  designSystem/src/main/java/com/example/designsystem/components/buttons/PlainTextButton.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/AflamiColorScheme.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/DarkColors.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/LigthColors.kt
  designSystem/src/main/res/drawable/ic_user_square.xml
  ui/src/main/java/com/example/ui/application/AflamiApp.kt
  ui/src/main/java/com/example/ui/navigation/NavGraph.kt
  ui/src/main/java/com/example/ui/navigation/Route.kt
  ui/src/main/java/com/example/ui/screens/login/LoginScreen.kt
  ui/src/main/java/com/example/ui/screens/login/LoginScreenRoute.kt
  ui/src/main/java/com/example/ui/screens/login/components/BackgroundCircleData.kt
  ui/src/main/java/com/example/ui/screens/login/components/GetBackgroundCircles.kt
  ui/src/main/java/com/example/ui/screens/login/components/GetPasswordTextFieldIcon.kt
  ui/src/main/java/com/example/ui/screens/login/components/LoginBackground.kt
  viewModel/src/main/java/com/example/viewmodel/login/LoginEffect.kt
  viewModel/src/main/java/com/example/viewmodel/login/LoginInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/login/LoginUiState.kt
  viewModel/src/main/java/com/example/viewmodel/login/LoginViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/shared/BaseViewModel.kt
  viewModel/src/test/java/com/example/viewmodel/ExampleUnitTest.kt
  viewModel/src/test/java/com/example/viewmodel/LoginViewModelTest.kt
  viewModel/src/test/java/com/example/viewmodel/SearchByCountryViewModelTest.kt
  viewModel/src/test/java/com/example/viewmodel/utils/viewmodelHelper/createLoginViewModel.kt
Labels: feature

#180 Resolve tv show problem that prevent the Tv shows to appear.
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/TvShowDao.kt
Labels: fix

#179 Feature/registeration
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  designSystem/src/main/java/com/example/designsystem/components/LoadingContainer.kt
  ui/src/main/java/com/example/ui/navigation/NavGraph.kt
  ui/src/main/java/com/example/ui/navigation/Route.kt
  ui/src/main/java/com/example/ui/screens/login/LoginScreen.kt
  ui/src/main/java/com/example/ui/screens/register/RegisterScreen.kt
  ui/src/main/java/com/example/ui/screens/register/RegisterScreenRout.kt
  ui/src/main/java/com/example/ui/screens/register/components/RegisterWebView.kt
  ui/src/main/java/com/example/ui/utils/webViewhelper.kt
  viewModel/build.gradle.kts
  viewModel/src/main/java/com/example/viewmodel/login/LoginEffect.kt
  viewModel/src/main/java/com/example/viewmodel/login/LoginViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/register/RegisterEffect.kt
  viewModel/src/main/java/com/example/viewmodel/register/RegisterUiState.kt
  viewModel/src/main/java/com/example/viewmodel/register/RegisterViewModel.kt
Labels: feature

#183 Add register and reset password URLs to CI
  .github/workflows/deploy.yml
  .github/workflows/test_coverage.yml
Labels: enhancement

#185 Refactor Date Handling
  app/src/main/java/com/amsterdam/aflami/di/mapperModule.kt
  entity/src/main/java/com/example/entity/Movie.kt
  entity/src/main/java/com/example/entity/TvShow.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/AflamiDatabase.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/converter/LocalDateConverter.kt
  repository/src/main/java/com/example/repository/dto/local/LocalMovieDto.kt
  repository/src/main/java/com/example/repository/dto/local/LocalTvShowDto.kt
  repository/src/main/java/com/example/repository/mapper/local/MovieLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/MovieWithCategoriesLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/TvShowLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/TvShowWithCategoryLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/MovieRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/TvShowDetailsRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/TvShowRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remoteToLocal/MovieRemoteLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/remoteToLocal/TvShowRemoteLocalMapper.kt
  repository/src/main/java/com/example/repository/utils/DateParser.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeUiStateMapper.kt
  viewModel/src/main/java/com/example/viewmodel/movieDetails/MovieDetailsUiStateMapper.kt
  viewModel/src/main/java/com/example/viewmodel/search/mapper/MediaItemUiStateMapper.kt
  viewModel/src/main/java/com/example/viewmodel/search/mapper/MovieItemUiStateMapper.kt
  viewModel/src/main/java/com/example/viewmodel/seriesDetails/SeriesDetailsStateMapper.kt
  viewModel/src/main/java/com/example/viewmodel/topRated/TopRatedUiStateMapper.kt
Labels: refactor

#195 Feature: Login remote data source
  app/src/main/java/com/amsterdam/aflami/di/remoteDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/serviceModule.kt
  domain/src/main/java/com/example/domain/exceptions/AflamiException.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/api/AuthenticationApiService.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/client/RetrofitClient.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/AuthenticationRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/AuthenticationServiceProvider.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/implementation/AuthenticationServiceProviderImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/utils/apiHandler/responseCall.kt
  repository/src/main/java/com/example/repository/datasource/remote/AuthenticationRemoteSource.kt
  repository/src/main/java/com/example/repository/dto/remote/authentication/AuthenticationResponseDto.kt
  repository/src/main/java/com/example/repository/dto/remote/authentication/CreateSessionDto.kt
  repository/src/main/java/com/example/repository/dto/remote/authentication/CreateSessionResponseDto.kt
Labels: feature

#193 Fix: Use HorizontalPager in MovieDetailsScreen
  ui/src/main/java/com/example/ui/screens/movieDetails/MovieDetailsScreen.kt
Labels: fix

#191 Feature: complete login with credential and as guest
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/mapperModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  designSystem/proguard-rules.pro
  domain/src/main/java/com/example/domain/repository/AuthenticationRepository.kt
  domain/src/main/java/com/example/domain/useCase/authentication/GetsSessionType.kt
  domain/src/main/java/com/example/domain/useCase/authentication/LoginAsGuestUseCase.kt
  domain/src/main/java/com/example/domain/utils/SessionType.kt
  gradle/libs.versions.toml
  localDatasource/build.gradle.kts
  localDatasource/src/main/java/com/example/localdatasource/dataStore/appPreferences/AppDataStorePreferences.kt
  localDatasource/src/main/java/com/example/localdatasource/dataStore/datasource/AppPreferences.kt
  localDatasource/src/main/java/com/example/localdatasource/dataStore/datasource/AuthenticationLocalDataSourceImpl.kt
  repository/src/main/java/com/example/repository/datasource/local/AuthenticationLocalSource.kt
  repository/src/main/java/com/example/repository/mapper/local/SessionTypeMapper.kt
  repository/src/main/java/com/example/repository/repository/AuthenticationRepositoryImpl.kt
  ui/src/main/java/com/example/ui/application/AflamiApp.kt
  ui/src/main/java/com/example/ui/application/GetStartDestination.kt
  ui/src/main/java/com/example/ui/screens/home/sections/BlurredMoviePoster.kt
  ui/src/main/java/com/example/ui/screens/login/LoginScreen.kt
  ui/src/main/java/com/example/ui/screens/login/components/GetLoginErrorMessage.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/example/viewmodel/application/ApplicationUiState.kt
  viewModel/src/main/java/com/example/viewmodel/application/ApplicationViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/login/LoginUiState.kt
  viewModel/src/main/java/com/example/viewmodel/login/LoginViewModel.kt
  viewModel/src/test/java/com/example/viewmodel/LoginViewModelTest.kt
  viewModel/src/test/java/com/example/viewmodel/utils/viewmodelHelper/createLoginViewModel.kt
Labels: feature

#192 Test/remote data source test coverage
  remoteDatasource/build.gradle.kts
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/TvRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/implementation/TvShowsServiceProviderImpl.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/CategoryRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/CategoryServiceProviderImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/CountryRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/CountryServiceProviderImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/MovieRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/MovieServiceProviderImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/TvRemoteDataSourceImplTest.kt
  remoteDatasource/src/test/java/com/example/remotedatasource/TvShowsServiceProviderImplTest.kt
Labels: Testing

#198 Add Proguard rules for Room DB and Kotlinx Serialization
  app/proguard-rules.pro
  designSystem/proguard-rules.pro
  gradle.properties
  repository/proguard-rules.pro
Labels: fix, chore

#203 Fix missing episodes in series details screen
  remoteDatasource/src/main/java/com/example/remotedatasource/api/TvShowsApiService.kt
  repository/src/main/java/com/example/repository/dto/remote/EpisodeDto.kt
Labels: fix

#196 Feature/home continue watching
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/mapperModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  domain/src/main/java/com/example/domain/repository/WatchHistoryRepository.kt
  domain/src/main/java/com/example/domain/useCase/AddWatchHistoryUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetContinueWatchingMoviesUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetHomeScreenDataUseCase.kt
  domain/src/main/java/com/example/domain/useCase/GetMovieDetailsUseCase.kt
  entity/src/main/java/com/example/entity/WatchHistory.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/AflamiDatabase.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/daos/WatchHistoryDao.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/MovieLocalDataSourceImpl.kt
  localDatasource/src/main/java/com/example/localdatasource/roomDataBase/datasource/WatchHistoryLocalDataSourceImpl.kt
  repository/src/main/java/com/example/repository/datasource/local/MovieLocalSource.kt
  repository/src/main/java/com/example/repository/datasource/local/WatchHistoryLocalDataSource.kt
  repository/src/main/java/com/example/repository/dto/local/WatchHistoryDto.kt
  repository/src/main/java/com/example/repository/dto/local/utils/DatabaseConstants.kt
  repository/src/main/java/com/example/repository/mapper/local/WatchHistoryMapper.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/example/repository/repository/WatchHistoryRepositoryImpl.kt
  ui/src/main/java/com/example/ui/navigation/NavGraph.kt
  ui/src/main/java/com/example/ui/navigation/Route.kt
  ui/src/main/java/com/example/ui/screens/continueWatching/ContinueWatchingScreen.kt
  ui/src/main/java/com/example/ui/screens/continueWatching/ContinueWatchingScreenRoute.kt
  ui/src/main/java/com/example/ui/screens/continueWatching/component/ContinueWatchingMoviesGrid.kt
  ui/src/main/java/com/example/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/example/ui/screens/home/sections/continueWatchingSection.kt
  ui/src/main/java/com/example/ui/screens/resetPassword/ResetPasswordScreen.kt
  ui/src/main/java/com/example/ui/screens/resetPassword/ResetPasswordScreenRout.kt
  ui/src/main/java/com/example/ui/screens/resetPassword/components/ResetPasswordWebView.kt
  viewModel/src/main/java/com/example/viewmodel/continueWatching/ContinueWatchingEffect.kt
  viewModel/src/main/java/com/example/viewmodel/continueWatching/ContinueWatchingInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/continueWatching/ContinueWatchingUiState.kt
  viewModel/src/main/java/com/example/viewmodel/continueWatching/ContinueWatchingUiStateMapper.kt
  viewModel/src/main/java/com/example/viewmodel/continueWatching/ContinueWatchingViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeEffect.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeUiState.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeUiStateMapper.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/movieDetails/MovieDetailsViewModel.kt
Labels: feature

#200 Change category mapping from extension functions to regular functions
  repository/src/main/java/com/example/repository/mapper/local/MovieGenreLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/local/TvShowGenreLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/MovieRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/TvShowDetailsRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remote/TvShowRemoteMapper.kt
  repository/src/main/java/com/example/repository/mapper/remoteToLocal/MovieGenreIdsRemoteLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/remoteToLocal/TvShowGenreIdsRemoteLocalMapper.kt
  repository/src/main/java/com/example/repository/mapper/shared/GenreMapper.kt
Labels: refactor

#167 Feature: Add You must login dialog UI to Movie and Series details screen
  app/src/main/java/com/amsterdam/aflami/AppLogger.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/AflamiColorScheme.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/DarkColors.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/LigthColors.kt
  remoteDatasource/build.gradle.kts
  ui/src/main/java/com/example/ui/components/MustLoginDialog.kt
  ui/src/main/java/com/example/ui/screens/movieDetails/ExtrasSectionItemInfo.kt
  ui/src/main/java/com/example/ui/screens/movieDetails/LoginDialogType.kt
  ui/src/main/java/com/example/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/example/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  viewModel/src/main/java/com/example/viewmodel/movieDetails/MovieDetailsEffect.kt
  viewModel/src/main/java/com/example/viewmodel/movieDetails/MovieDetailsIntractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/movieDetails/MovieDetailsUiState.kt
  viewModel/src/main/java/com/example/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/seriesDetails/SeriesDetailsEffect.kt
  viewModel/src/main/java/com/example/viewmodel/seriesDetails/SeriesDetailsInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/seriesDetails/SeriesDetailsUiState.kt
  viewModel/src/main/java/com/example/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
  viewModel/src/main/java/com/example/viewmodel/shared/movieAndSeriseDetails/MovieAndSeriesDetailsDialogType.kt
Labels: feature

#205 test: Add unit tests for MovieDetailsViewModel with coverage 100%
  viewModel/src/main/java/com/example/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/test/java/com/example/viewmodel/movieDetails/MovieDetailsViewModelTest.kt
Labels: Testing

#197 Add mood picker feature
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  designSystem/src/main/java/com/example/designsystem/components/Dialog.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/AflamiColorScheme.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/DarkColors.kt
  designSystem/src/main/java/com/example/designsystem/theme/colors/LigthColors.kt
  domain/src/main/java/com/example/domain/models/Mood.kt
  domain/src/main/java/com/example/domain/repository/MovieRepository.kt
  domain/src/main/java/com/example/domain/useCase/GetMoviesByMoodUseCase.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/api/MovieApiService.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/datasource/MovieRemoteDataSourceImpl.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/MovieServiceProvider.kt
  remoteDatasource/src/main/java/com/example/remotedatasource/serviceProvider/implementation/MovieServiceProviderImpl.kt
  repository/src/main/java/com/example/repository/datasource/remote/MovieRemoteSource.kt
  repository/src/main/java/com/example/repository/mapper/local/MovieGenreLocalMapper.kt
  repository/src/main/java/com/example/repository/repository/MovieRepositoryImpl.kt
  ui/src/main/java/com/example/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/example/ui/screens/home/component/MoodPickerCard.kt
  ui/src/main/java/com/example/ui/screens/home/component/MovieMoodPickerDialogDialog.kt
  ui/src/main/java/com/example/ui/screens/home/model/CardMood.kt
  ui/src/main/java/com/example/ui/screens/home/sections/MoodPickerSection.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeInteractionListener.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeUiState.kt
  viewModel/src/main/java/com/example/viewmodel/home/HomeViewModel.kt
Labels: feature

#184 Feature/add cast view model test
  viewModel/src/test/java/com/example/viewmodel/CastViewModelTest.kt
Labels: Testing

#201 Test: RecentSearchHandlerImpl
  repository/src/test/java/com/example/repository/mapper/local/CountryLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/CountryRemoteToLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieCategoryLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieGenreLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/MovieWithCategoriesLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/RecentSearchLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowCategoryLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowGenreLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/TvShowWithCategoryLocalMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/local/testFactory/TestMovieCategoryFactory.kt
  repository/src/test/java/com/example/repository/mapper/local/testFactory/TestMovieFactory.kt
  repository/src/test/java/com/example/repository/mapper/local/testFactory/TvShowCategoryTestFactory.kt
  repository/src/test/java/com/example/repository/mapper/remote/CategoryRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/GalleryRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/MovieRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/PostersRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/TvShowRemoteMapperTest.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/RemoteCategoryDtoFactory.kt
  repository/src/test/java/com/example/repository/mapper/remote/testFactory/createRemoteMovieGalleryResponse.kt
  repository/src/test/java/com/example/repository/utils/RecentSearchHandlerImplTest.kt
  repository/src/test/java/com/example/repository/utils/createLocalSearchDto.kt
Labels: Testing

#214 Handle dependencies and move constant versions in catalog version
  app/build.gradle.kts
  designSystem/build.gradle.kts
  domain/build.gradle.kts
  entity/build.gradle.kts
  gradle/libs.versions.toml
  remoteDatasource/build.gradle.kts
  repository/build.gradle.kts
  ui/build.gradle.kts
  viewModel/build.gradle.kts
Labels: enhancement

#215 refactor: delete empty and unused files
  designSystem/src/main/java/com/amsterdam/designsystem/components/CustomMoodPickerCard.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/relation/CategoryWithMovies.kt
  repository/src/main/java/com/amsterdam/repository/dto/local/relation/SearchWithMovies.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/component/PopularSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/NoMovieImageHolder.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/mapper/MovieMapper.kt
Labels: enhancement

#213 Refactor: split usecases into packages
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  domain/src/main/java/com/amsterdam/domain/useCase/common/AddWatchHistoryUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/details/GetEpisodesBySeasonNumberUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/details/GetMovieCastUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/details/GetMovieDetailsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/details/GetTvShowDetailsUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetContinueWatchingMoviesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetHomeScreenDataUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetMoviesByMoodUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetPopularMoviesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetTopRatedMoviesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetUpcomingMoviesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/search/GetAndFilterMoviesByKeywordUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/search/GetAndFilterTvShowsByKeywordUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/search/GetMoviesByActorUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/search/GetMoviesByCountryUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/search/GetSuggestedCountriesUseCase.kt
  domain/src/main/java/com/amsterdam/domain/useCase/search/RecentSearchesUseCase.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetAndFilterMoviesByKeywordUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetAndFilterTvShowsByKeywordUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetHomeScreenDataUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetMovieCastUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetMovieDetailsUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetMoviesByActorUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetMoviesByCountryUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetPopularMoviesUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetSuggestedCountriesUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetTopRatedMoviesUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/GetUpcomingMoviesUseCaseTest.kt
  domain/src/test/java/com/amsterdam/domain/useCase/RecentSearchesUseCaseTest.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/cast/CastViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/continueWatching/ContinueWatchingViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/SearchActorViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/topRated/TopRatedViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/CastViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/SearchByActorViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/SearchByCountryViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/home/HomeViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModelTest.kt
Labels: enhancement

#217 Refactor design system module
  designSystem/src/main/java/com/amsterdam/designsystem/DesignSystem.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/CenterOfScreenContainer.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/LoadingContainer.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/Slider.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/snackBar/SnackBar.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/snackBar/SnackBarStatus.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/snackBar/SnackBarVisuals.kt
  ui/src/main/java/com/amsterdam/ui/components/BaseCard.kt
  ui/src/main/java/com/amsterdam/ui/components/EpisodeCard.kt
  ui/src/main/java/com/amsterdam/ui/components/RatingChip.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/component/MovieMoodPickerDialogDialog.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/component/PopularMovieCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/ReviewCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
Labels: refactor

#218 Fix: modify crashylitcs to be in release mode only
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
Labels: fix

#219 Implement Shimmer Effect In Home Screen
  app/src/main/java/com/amsterdam/aflami/di/useCaceModule.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/RoundedShimmerPlaceholder.kt
  designSystem/src/main/java/com/amsterdam/designsystem/theme/colors/AflamiColorScheme.kt
  designSystem/src/main/java/com/amsterdam/designsystem/theme/colors/DarkColors.kt
  designSystem/src/main/java/com/amsterdam/designsystem/theme/colors/LigthColors.kt
  designSystem/src/main/java/com/amsterdam/designsystem/utils/modifierExtensions/ShimmerEffect.kt
  domain/src/main/java/com/amsterdam/domain/useCase/home/GetHomeScreenDataUseCase.kt
  ui/src/main/java/com/amsterdam/ui/components/NoNetworkContainer.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/ContinueWatchingSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/PopularSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/TopRatingSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/UpcomingMoviesSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/continueWatchingSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/placeholder/MovieSectionPlaceholder.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/placeholder/PopularSectionPlaceholder.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/placeholder/UpcomingMoviesSectionPlaceholder.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/topRatingSection.kt
  ui/src/main/res/values-ar/string.xml
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/resetPassword/ResetPasswordViewModel.kt
Labels: feature

#224 Fix search UI states
  app/src/main/java/com/amsterdam/aflami/di/viewModelModule.kt
  ui/src/main/java/com/amsterdam/ui/components/NoNetworkContainer.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/actorSearch/SearchByActorScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/countrySearch/SearchByCountryScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/countrySearch/components/MoviesVerticalGrid.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/SearchActorEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/SearchActorInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchIntractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
Labels: fix

#228 Fix: fix login effect
  ui/src/main/java/com/amsterdam/ui/screens/login/LoginScreen.kt
Labels: fix

#229 Fix: fix slider image appearing in scroll
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/BlurredMoviePoster.kt
Labels: fix

#226 refactor: Remove invalid epoch day check in LocalDateConverter causin…
  localDatasource/src/main/java/com/amsterdam/localdatasource/roomDataBase/converter/LocalDateConverter.kt
Labels: fix

#233 Refactor: add start exploring section
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/ExploreMoviesAndShows.kt
Labels: feature

#232 fix/imageViewer
  imageViewer/src/main/java/com/amsterdam/imageviewer/classification/model/SafetyRule.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/coil/ImageLoaderFactory.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/coil/providers/ImageClassifierProvider.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/coil/providers/ImageLoaderProvider.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/firebase/FirebaseModelManager.kt
Labels: fix

#223 feature: Add movie genres to UI
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/PopularSection.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/shared/uiStates/MovieItemUiState.kt
Labels: feature

#237 Test/fix broken test in view model
  viewModel/build.gradle.kts
  viewModel/src/test/java/com/amsterdam/viewmodel/CastViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/LoginViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/baseViewModel/BaseViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/baseViewModel/TestViewModel.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/home/HomeViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModelTest.kt
  viewModel/src/test/java/com/amsterdam/viewmodel/utils/entityHelper/createMovie.kt
Labels: Testing

#227 Test/repository test coverage
  repository/src/test/java/com/amsterdam/repository/repository/AuthenticationRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/CategoryRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/CountryRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/RecentSearchRepositoryImplTest.kt
  repository/src/test/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImplTest.kt
Labels: Testing

#245 Fix Reset Password Does Not Work
  viewModel/src/main/java/com/amsterdam/viewmodel/resetPassword/ResetPasswordViewModel.kt
Labels: fix

#258 Fix/make password stars
  designSystem/src/main/java/com/amsterdam/designsystem/components/TextField.kt
Labels: fix

#249 Fix/bottom navbar text overflows and survive in configuration changes
  designSystem/src/main/java/com/amsterdam/designsystem/components/bottomNavBar/BottomNavBar.kt
  ui/src/main/java/com/amsterdam/ui/navigation/BottomNaviagtion.kt
Labels: fix

#259 Fix/text field hint in search by actor
  ui/src/main/java/com/amsterdam/ui/screens/search/actorSearch/SearchByActorScreen.kt
Labels: fix

#260 Fix no search data found
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/actorSearch/SearchByActorScreen.kt
Labels: fix

#243 Update explore movies and shows padding
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/ExploreMoviesAndShows.kt
Labels: fix

#252 Fix: fix login appears briefly on startup
  ui/src/main/java/com/amsterdam/ui/application/AflamiApp.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/application/ApplicationViewModel.kt
Labels: fix

#235 Fix/filtering section state & chips UI issue
  designSystem/src/main/java/com/amsterdam/designsystem/components/chip/Chip.kt
  designSystem/src/main/res/values/strings.xml
  entity/src/main/java/com/amsterdam/entity/category/MovieGenre.kt
  entity/src/main/java/com/amsterdam/entity/category/TvShowGenre.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/filterDialog/FilterDialog.kt
  ui/src/main/res/values/strings.xml
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchUiState.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
Labels: fix

#265 Fix/conflict world tour & actor search
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
Labels: fix

#270 fix: hide seasons with no episodes in series details
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
Labels: fix

#266 Fix mode picker dialog landscape
  designSystem/src/main/java/com/amsterdam/designsystem/components/Dialog.kt
  designSystem/src/main/java/com/amsterdam/designsystem/theme/colors/DarkColors.kt
  designSystem/src/main/java/com/amsterdam/designsystem/theme/colors/LigthColors.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/component/MovieMoodPickerDialogDialog.kt
Labels: fix

#256 Fix: Review in details screen
  designSystem/src/main/java/com/amsterdam/designsystem/components/ExpandableText.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/EmptyStateText.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/ReviewCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/ReviewSection.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiStateMapper.kt
Labels: fix

#273 enhance/model-download
  gradle/libs.versions.toml
  imageViewer/src/main/AndroidManifest.xml
  imageViewer/src/main/java/com/amsterdam/imageviewer/FirebaseModelInitializer.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/classification/ClassifierConfig.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/classification/ImageClassifierFactory.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/coil/ImageLoaderFactory.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/coil/providers/ImageClassifierProvider.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/coil/providers/ImageLoaderProvider.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/firebase/FirebaseModelInitializer.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/firebase/FirebaseModelManager.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/firebase/FirebaseNsfwModelManager.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/firebase/ModeDownloadState.kt
  imageViewer/src/main/java/com/amsterdam/imageviewer/ui/SafeImageView.kt
Labels: refactor

#279 Handle gallery grid in details screen
  ui/src/main/java/com/amsterdam/ui/components/AdaptiveGrid.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/GallerySection.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
Labels: fix, enhancement

#274 Fix/more like this section not clickable in details
  ui/src/main/java/com/amsterdam/ui/components/BaseCard.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/MoreLikeSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsIntractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsUiStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsEffect.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsInteractionListener.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/shared/movieAndSeriseDetails/SimilarMovieUiState.kt
Labels: fix

#278 Fix/movie details images pager indicator
  designSystem/src/main/java/com/amsterdam/designsystem/components/ImageErrorIndicator.kt
  ui/src/main/java/com/amsterdam/ui/components/appBar/DefaultAppBar.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
Labels: fix

#284 refactor: add padding top between ActorCard and ActorName and add pre…
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/ActorCard.kt
Labels: fix

#281 Handle series posters pager and indicator
  domain/src/main/java/com/amsterdam/domain/useCase/details/GetTvShowDetailsUseCase.kt
  repository/src/main/java/com/amsterdam/repository/mapper/remote/TvShowDetailsRemoteMapper.kt
  ui/src/main/java/com/amsterdam/ui/components/details/DetailsPosterPager.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsStateMapper.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsUiState.kt
Labels: fix, feature

#288 Fix: fix details UI jumping
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/UpcomingMoviesSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
Labels: fix

#290 Fix Section Shows When Data is Empty In Detailes Screens
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/CastSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/DescriptionSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsStateMapper.kt
Labels: fix

#271 Fix & Refactor Search Screen Layout
  designSystem/src/main/java/com/amsterdam/designsystem/components/TabLayout.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/RecentSearchesSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/SearchScreenHeaderSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/SuccessMediaItemsSection.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/SuggestionsHub.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/sections/SuggestionsHubSection.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
Labels: fix, refactor

#289 Fix: handle navigation double clicks and dont use any for navigation
  designSystem/src/main/java/com/amsterdam/designsystem/components/bottomNavBar/NavigationBar.kt
  designSystem/src/main/java/com/amsterdam/designsystem/components/bottomNavBar/NavigationBarItem.kt
  ui/src/main/java/com/amsterdam/ui/application/AflamiApp.kt
  ui/src/main/java/com/amsterdam/ui/application/GetStartDestination.kt
  ui/src/main/java/com/amsterdam/ui/components/bottomNavigation/BottomBarItems.kt
  ui/src/main/java/com/amsterdam/ui/components/bottomNavigation/BottomNavBar.kt
  ui/src/main/java/com/amsterdam/ui/components/bottomNavigation/BottomNaviagtion.kt
  ui/src/main/java/com/amsterdam/ui/navigation/NavGraph.kt
  ui/src/main/java/com/amsterdam/ui/navigation/Route.kt
  ui/src/main/java/com/amsterdam/ui/screens/cast/CastScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/continueWatching/ContinueWatchingScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/login/LoginScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/register/RegisterScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/resetPassword/ResetPasswordScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/actorSearch/SearchByActorScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/countrySearch/SearchByCountryScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/search/keywordSearch/SearchScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/topRated/TopRatedScreen.kt
  ui/src/main/java/com/amsterdam/ui/utils/safeNavigateExtensions.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/cast/CastViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/continueWatching/ContinueWatchingViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/login/LoginViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/register/RegisterViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/resetPassword/ResetPasswordViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/shared/BaseViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/topRated/TopRatedViewModel.kt
Labels: fix

#303 Refactor: Update movie details app bar to be sticky
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
Labels: fix, refactor

#264 Fix: Company production images
  imageViewer/src/main/java/com/amsterdam/imageviewer/ui/SafeImageView.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/sections/BlurredMoviePoster.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/components/CompanyCard.kt
Labels: fix

#295 Add no internet container in top rated screen
  ui/src/main/java/com/amsterdam/ui/screens/topRated/TopRatedScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/topRated/TopRatedViewModel.kt
Labels: fix, refactor

#293 Listen to configuration changes in All Screens
  app/src/main/java/com/amsterdam/aflami/di/apiServiceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/localDataSourceModule.kt
  app/src/main/java/com/amsterdam/aflami/di/repositoryModule.kt
  app/src/main/java/com/amsterdam/aflami/di/useCaseModule.kt
  domain/src/main/java/com/amsterdam/domain/repository/AppPreferencesRepository.kt
  domain/src/main/java/com/amsterdam/domain/useCase/preferences/ManageLocaleLanguageUseCase.kt
  localDatasource/src/main/java/com/amsterdam/localdatasource/dataStore/AppPreferencesImpl.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/client/RetrofitClient.kt
  repository/src/main/java/com/amsterdam/repository/datasource/local/AppPreferences.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/MovieWatchHistoryMapper.kt
  repository/src/main/java/com/amsterdam/repository/mapper/local/TvShowWatchHistoryMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/AppPreferencesRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/CategoryRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/CountryRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/RecentSearchRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/utils/DeviceLanguage.kt
  ui/src/main/java/com/amsterdam/ui/application/AflamiApp.kt
  ui/src/main/java/com/amsterdam/ui/screens/continueWatching/ContinueWatchingScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/home/HomeScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/movieDetails/MovieDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/seriesDetails/SeriesDetailsScreen.kt
  ui/src/main/java/com/amsterdam/ui/screens/topRated/TopRatedScreen.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/application/ApplicationViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/cast/CastViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/continueWatching/ContinueWatchingViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/movieDetails/MovieDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/actorSearch/ActorSearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/countrySearch/CountrySearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/search/keywordSearch/SearchViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/seriesDetails/SeriesDetailsViewModel.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/topRated/TopRatedViewModel.kt
Labels: fix, enhancement

#307 Fix wrong mapping to argument to Load search results
  app/src/main/java/com/amsterdam/aflami/di/apiServiceModule.kt
  remoteDatasource/src/main/java/com/amsterdam/remotedatasource/client/RetrofitClient.kt
  repository/src/main/java/com/amsterdam/repository/repository/CategoryRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/CountryRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/TvShowRepositoryImpl.kt
  repository/src/main/java/com/amsterdam/repository/repository/WatchHistoryRepositoryImpl.kt
Labels: fix

#310 fix: update upcoming and similar movies to use backdrop images
  repository/src/main/java/com/amsterdam/repository/mapper/remote/MovieDetailRemoteMapper.kt
  repository/src/main/java/com/amsterdam/repository/repository/MovieRepositoryImpl.kt
Labels: refactor

#311 refactor: handle mood categories in mood picker
  domain/src/main/java/com/amsterdam/domain/models/Mood.kt
  viewModel/src/main/java/com/amsterdam/viewmodel/home/HomeUiState.kt
Labels: fix
